### ISSUE TITLE
support addition of new datasets with versions

### ISSUE THREAD

**Issue by lwaldron** [waldronlab/curatedMetagenomicData#102]
One fix would be if you can create symbolic links from older files to newer files for those that have not changed in the new version. For now I have restricted `inst/extdata/versions.txt` to the previous date.

**Comment by schifferl** [comment]
Fixed with e47adbc!

**Comment by lwaldron** [comment]
This commit was " more performant databases " ? Could you explain here how
the issue was resolved?

**Comment by schifferl** [comment]
Yikes! I meant d8a45037b00fd6b79ad2eb33f61ceb0e90d59069

**Comment by lwaldron** [comment]
Looks like the right one :). For the record, perhaps an explanation of how
versioning works would be apropos in this thread, and at appropriate places
in the documentation for users and developers.

**Comment by schifferl** [comment]
Ok, the essence of the resolution is this:

```
title_df %>%
    arrange(desc(run_date), study, data_type, body_site) %>%
    distinct(study, data_type, body_site, .keep_all = TRUE) %>%
```

When each named function is initialized the latest version available becomes the default version returned. This accommodates for potentially different latest dates between different datasets.

Then the `curatedMetagenomicData()` function had the `cmdversion` argument removed and will just return the latest version. Older versions are still accessible, just not in bulk from the `curatedMetagenomicData()` function – it would be necessary to use the named function and specify the desired `cmdversion`.

This was the best way to resolve for the time being but as per your documentation comment – I think the entire pipeline should become it's own `R` package, probably named `curatedMetagenomicDataPipeline` and be way more documented. For now, I will double check the present user documentation and make sure it is sufficient.

I imagine that `curatedMetagenomicDataPipeline` is where `SummarizedExperiment` can be implemented, and the outputs from there will be used in `curatedMetagenomicData` v 2.0.0.
