### ISSUE TITLE
unit test to check that datasets are still present

### ISSUE THREAD

**Issue by lwaldron** [waldronlab/curatedMetagenomicData#103]
Would not be a bad idea to:
1. check downloading all metaphlan profiles with `dryrun=FALSE`
2. check downloading all datasets with `dryrun=TRUE`

**Comment by lwaldron** [comment]
https://github.com/waldronlab/curatedMetagenomicData/blob/master/tests/testthat/test-curatedMetagenomicData.R will have to be updated. Leave this issue open to indicate that an updated unit test accomplishes these things. Under issue #165

**Comment by lwaldron** [comment]
related to #192

**Comment by schifferl** [comment]
This will be covered by #219, closing.
