### ISSUE TITLE
putative error in metadata for QinJ_2012

### ISSUE THREAD

**Issue by karchern** [waldronlab/curatedMetagenomicData#107]
Hi Guys,

In the metadata for QinJ_2012, the subject "CON-103" is listed 5 times (with different sample IDs, of course). I believe this is an error, as to my knowledge the study did not have any sort of time series / mutliple sampling.

Cheers!

**Comment by schifferl** [comment]
Thanks, nick! Edo and I will look into it and provide corrected metadata.

**Comment by paolinomanghi** [comment]
Ok, sto operando

**Comment by schifferl** [comment]
This issue was moved to waldronlab/curatedMetagenomicDataCuration#19
