### ISSUE TITLE
unit test of combined_metadata against template

### ISSUE THREAD

**Issue by lwaldron** [waldronlab/curatedMetagenomicData#108]
combined_metadata should be checked against template.csv to ensure validity. This is already done at https://github.com/waldronlab/curatedMetagenomicDataCuration but should also be done in curatedMetagenomicData.

**Comment by schifferl** [comment]
@lwaldron do you think we need to do this twice? Or the first time in the curation repo is sufficient?

**Comment by schifferl** [comment]
Never mind, this makes more sense after reading #109. I am going to combine and summarize the two issues and then write the test.

**Comment by lwaldron** [comment]
Yep - just a way to know when cMD is or is not up to date with cMDCuration, and to know what differences there are. If `combined_metadata` here doesn't match with `template.csv` here that would be an warning. If `template.csv` here does not match `template.csv` at cMDCuration that would only be a note. Eventually the pipeline will make these transfers more seamless, but in any case we want to make sure that changes at cMDCuration do not get forgotten there.

**Comment by lwaldron** [comment]
This actually should not be a part of the curatedMetagenomicData package, but a check as part of the GHA creating combined_metadata.rda in issue #174 @jwokaty. If this check fails, either don't create the PR, or just have a "checks failed" badge with it. 

See the [checkCuration](https://github.com/waldronlab/curatedMetagenomicDataCuration/blob/master/man/checkCuration.Rd) function in curatedMetagenomicDataCuration for doing this check.
