### ISSUE TITLE
"unknown" converted to NA

### ISSUE THREAD

**Issue by lwaldron** [waldronlab/curatedMetagenomicData#110]
"Unknown" is currently not allowed anywhere in the template.csv, so this conversion should be necessary, and should probably be removed in case we ever do decide to have an "unknown" value in the metadata:

https://github.com/waldronlab/curatedMetagenomicData/blob/3cc40237029df70241b4d38cf5125a7f96b37270/data-raw/format_metadata.R#L4

**Comment by schifferl** [comment]
`"unknown"` has been removed, and will otherwise be handled by the curation repo into the future

**Comment by lwaldron** [comment]
It's good practice to link to the relevant changeset when closing an issue (I think this one is https://github.com/waldronlab/curatedMetagenomicData/commit/8cd5809e769c7966c20d3f7dbab2602cf1a175d9#diff-ae2c0b0f3672ae01bab0d4069c11183d). You can do so by including it in the commit message, e.g.: 

`commit -m "Do not treat 'unknown' as NA. 'unknown is no longer allowed by curation template. Closes #110.`" 

(This commit message is also more informative than "Update format_metadata.R")
