### ISSUE TITLE
automate the integration of vignette updates into package website

### ISSUE THREAD

**Issue by edoardopasolli** [waldronlab/curatedMetagenomicData#111]
I added in the page with the included datasets (https://waldronlab.github.io/curatedMetagenomicData/datasets-included/) the figure that shows the read depth for each dataset. Are you ok with this?
The link points to the figure that I copied from the devel vignette and saved as /curatedMetagenomicData/assets/img/datasets_depth.png. Or is it better, if possible, to link directly to the same figure present in the vignette?

**Comment by lwaldron** [comment]
Yes, it needed to be done. Points out that we should automate this either by 1) embedding from the bioconductor.org vignette, or 2) with a Travis hook like I used on curatedMetagenomicDataCuration:
https://github.com/waldronlab/curatedMetagenomicDataCuration/blob/8cec61fdf8abee17d2336a99a5836d2638b55f02/.travis.yml#L16. 1. is simpler.

**Comment by schifferl** [comment]
I have relabeled this issue as "automate the integration of vignette updates into package website" because I think that is essentially what we are after. The figure looks good and should automatically be updated when things change – a Travis hook is the right strategy for that.

**Comment by lwaldron** [comment]
Thumbs up!

**Comment by lwaldron** [comment]
This would likely involve migrating existing pages or replacing them with pkgdown.

**Comment by schifferl** [comment]
This is done now, even though the vignettes still need work. Closing
