### ISSUE TITLE
Addition of 2 new datasets - Smith et al. Subramanian et al

### ISSUE THREAD

**Issue by Rrob123** [waldronlab/curatedMetagenomicData#113]
Suggestion to add 2 new datasets related to infant malnutrition. Details below:

Subramanian et al
Manuscript: https://www.ncbi.nlm.nih.gov/pubmed/23363771
Dataset: https://gordonlab.wustl.edu/Subramanian_6_14/Nature_2014_Processed_16S_rRNA_datasets.html

Smith et al
Manuscript: https://www.ncbi.nlm.nih.gov/pubmed/24896187
Dataset: https://gordonlab.wustl.edu/SuppData_2017.html

Many thanks,

R

**Comment by lwaldron** [comment]
Great datasets, but used 16S amplicon sequencing, so are not compatible with the curatedMetagenomicData WMS pipeline. It would be great to create another resource for amplicon sequencing, but we don't currently have resources to. The closest thing I know for 16S studies is https://qiita.ucsd.edu/.

**Comment by Rrob123** [comment]
Thanks for the response, didn't realise they were 16S! We are currently generating similar datasets with WMS so hope to be able include them here.

Thanks for a great resource!

All the best.

**Comment by lwaldron** [comment]
@nsegata corrected me that the Smith et al. paper does provide shotgun metagenomic data, and that metagenomic data do exist separately for the Subramanian et al. cohort. But both used 454 pyrosequencing, which presents different compatibility problems that he could explain better than me.

**Comment by lwaldron** [comment]
Closing the issue because we cannot process 454 pyrosequencing datasets through our pipeline as it exists.
