### ISSUE TITLE
issue on datasets of MetAML

### ISSUE THREAD

**Issue by hainguyenct** [waldronlab/curatedMetagenomicData#114]
Dear authors,
I read your paper:
"Machine Learning Meta-analysis of Large Metagenomic Datasets: Tools and Biological
Insights" [1]
If I would like to extract gene abundances from 6 datasets like fig2 in this paper, How may I do that with curatedMetagenomicData?
I am able to extract T2D (344 samples): `QinJ_2012<-combined_metadata[combined_metadata$dataset_name=='QinJ_2012' & !is.na(combined_metadata$study_condition) ,]` and WT2D (96 samples) in curatedMetagenomicData, but the #samples of Cirrhosis in curatedMetagenomicData is 237 is not the same with the dataset in [1]: 232. Other datasets have the same issue.
Could you please tell me how to extract other datasets in [1]?
Thank you so much for your help.
Best regards,

**Comment by edoardopasolli** [comment]
This is the correspondence between the datasets used in our previous Plos CompBio paper ("Machine Learning Meta-analysis of Large Metagenomic Datasets: Tools and Biological Insights") and the new paper based on curatedMetagenomicData:
- Cirrhosis -> QinN_2014
- Colorectal -> ZellerG_2014
- IBD -> NielsenHB_2014
- Obesity -> LeChatelierE_2013
- T2D -> QinJ_2012
- WT2D -> KarlssonFH_2013

But please aware that:
- as you observed, for T2D and WT2D the number of samples is exactly the same
- for Cirrhosis, Obesity and Colorectal a few more samples are available in curatedMetagenomicData now (but, apart these small differencens, they represent the same dataset)
- the IBD case done in our previous paper was based on this paper: "A human gut microbial gene catalogue established by metagenomic sequencing", while in curatedMetagenomicData we are including the dataset coming from "Identification  and  assembly  of  genomes  and  genetic  elements  in 
complex metagenomic samples without using reference genomes", which represents a significant larger extension of the previous work in terms of number of samples (from 124 to 396). So they are not directly comparable.

Additionally, please note that in our Plos CompBio paper we considered two type of features (as you can see, for example, from Figure 3):
- "Species abundance" that in curatedMetagenomicData are called "metaphlan_bugs_list"
- "Marker presence" that in curatedMetagenomicData are called "marker_presence"
There are four additional products (i.e. marker_abundance, genefamilies_relab, pathabundance_relab, pathcoverage) available in curatedMetagenomicData that were not analyzed in the Plos CompBio paper.

Finally, if you goal is to replicate the analysis done in the Plos CompBio paper but using curatedMetagenomicData, we are exactly doing this here (https://github.com/waldronlab/curatedMetagenomicData/tree/master/vignettes/extras - "Figure 1, Example 1: Classification"). Apart the differences that I explained earlier.

**Comment by hainguyenct** [comment]
Thank you so much for your help

**Comment by lwaldron** [comment]
This is related to Issue #61 that I opened a while ago. Edo, would you consider writing a function that selects these datasets and appends the diseases to the names as you show above? I would probably put this in the vignette rather than as a package function.

**Comment by lwaldron** [comment]
In that section we could also add the explanation you just gave, along with code for getting these datasets from the command line.

**Comment by lwaldron** [comment]
@edoardopasolli are you thinking to write a function to re-create this benchmarking dataset? Otherwise we can close this issue.

**Comment by edoardopasolli** [comment]
yes i'll write it
