### ISSUE TITLE
NCBI_accession corresponds to sample_id in place of run_id for HMP samples

### ISSUE THREAD

**Issue by fplaza** [waldronlab/curatedMetagenomicData#115]
Hello,

In the file _combined_metadata.rda_, the field NCBI_accession corresponds to the sample_id in place of the run_id for HMP samples.

For example:
dataset_name | sampleID | subjectID | NCBI_accession
HMP_2012 | SRS056519 | HMP_2012_765094712 | SRS056519
HMP_2012 | SRS018427 | HMP_2012_160218816 | SRS018427

Should be replaced by:
dataset_name | sampleID | subjectID | NCBI_accession
HMP_2012 | SRS056519 | HMP_2012_765094712 | SRR063503;SRR063504
HMP_2012 | SRS018427 | HMP_2012_160218816 | SRR059916;SRR059917

Thank you.

**Comment by edoardopasolli** [comment]
Thanks for catching this typo. I see that a similar problem is also affecting the KarlssonFH_2013 and the YuJ_2015 datasets.

@paolinomanghi could you generate the right NCBI_accession for these three datasets?

**Comment by fplaza** [comment]
@schifferl 
Yes, all the HMP samples are concerned.

**Comment by schifferl** [comment]
This issue was moved to waldronlab/curatedMetagenomicDataCuration#16
