### ISSUE TITLE
Wrong pubmed id for skin samples

### ISSUE THREAD

**Issue by ShaiberAlon** [waldronlab/curatedMetagenomicData#116]
Hi,

I was looking at the `combined_metadata` file (which is very helpful! thank you for it!), and I looked specifically at skin samples, and noticed that the pubmed id for the samples from the publication https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4185404/ have an increasing pubmed id, starting at the correct id (25279917) for the first sample in the table, but then increasing by one for each of the other samples, whereas it should be the same id.

**Comment by schifferl** [comment]
Glad you noticed, we will make sure it is resolved shortly.

**Comment by edoardopasolli** [comment]
@ShaiberAlon Do you have a recent version of the package? (looking at the first column "dataset_name" you should get 28 unique names/values).
The issue you reported was present in the past, but it should be fixed now (I don't see the error doing combined_metadata on the last version of the package).

Please let us know if this was the problem, thanks!

**Comment by ShaiberAlon** [comment]
Hi Lucas and Edoardo,

Thank you both for your quick response!
Edoardo, you are right, I have been using an old version. Sorry for this
mistake.

Thank you,

Alon

On Dec 6, 2017 12:02 PM, "edoardopasolli" <notifications@github.com> wrote:

@ShaiberAlon <https://github.com/shaiberalon> Do you have a recent version
of the package? (looking at the first column "dataset_name" you should get
28 unique names/values).
The issue you reported was present in the past, but it should be fixed now
(I don't see the error doing combined_metadata on the last version of the
package).

Please let us know if this was the problem, thanks!

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/waldronlab/curatedMetagenomicData/issues/116#issuecomment-349724223>,
or mute the thread

**Comment by edoardopasolli** [comment]
no problem, happy that you resolved the issue
