### ISSUE TITLE
adding curator

### ISSUE THREAD

**Issue by edoardopasolli** [waldronlab/curatedMetagenomicData#117]
since we are going to rebuild the package by fixing a few bugs in the metadata (as reported in another open issue), should we added the "curator" field? if yes, how we name it? and whick kind of information do we want to put (such as first+last name, email, etc.)?

**Comment by lwaldron** [comment]
How about a "curator" column that is free form, but filled like: Edoardo Pasolli <edoardo.pasolli@gmail.com>. Should be added to https://github.com/waldronlab/curatedMetagenomicDataCuration/blob/master/inst/extdata/template.csv as a required field.
