### ISSUE TITLE
explaining "study_condition" and "disease" fields

### ISSUE THREAD

**Issue by edoardopasolli** [waldronlab/curatedMetagenomicData#118]
An external user may have some difficulties in understanding how we defined the "study_condition" and "disease" fields. Should we clarify this aspect better somewhere?

**Comment by lwaldron** [comment]
I think the canonical location for variable documentation is in the "Description" column of https://github.com/waldronlab/curatedMetagenomicDataCuration/blob/master/inst/extdata/template.csv. If you would add this @edoardopasolli (and check the adequacy of the rest of the descriptions), then we'll convert this issue to one for @schifferl to parse this file to create automatic codebooks in the vignette and in the `combined_metadata` help page.

**Comment by schifferl** [comment]
This issue was moved to waldronlab/curatedMetagenomicDataCuration#18
