### ISSUE TITLE
Addition of Loomba et al. dataset

### ISSUE THREAD

**Issue by fplaza** [waldronlab/curatedMetagenomicData#119]
Could you add this dataset http://dx.doi.org/10.1016/j.cmet.2017.04.001 to curatedMetagenomicData?
The SRA files are available here: https://www.ncbi.nlm.nih.gov/bioproject/373901
Thanks

**Comment by edoardopasolli** [comment]
Great dataset, thanks for the suggestion!

**Comment by schifferl** [comment]
This issue was moved to waldronlab/curatedMetagenomicDataCuration#13
