### ISSUE TITLE
File of duplicate samples

### ISSUE THREAD

**Issue by lwaldron** [waldronlab/curatedMetagenomicData#120]
@paolinomanghi would you create a spreadsheet of duplicates, perhaps like this?
`study1   sampleID1   study2    sampleID2`

The assignment of "1" and "2" would be significant in that, when the user selects an option like `removeduplicates=TRUE`, the samples in study 2 would by default be the ones removed. I would relegate the smaller study to study 2, unless there is a better reason to think of one of the studies as the preferable default (like better metadata or data quality). 

If a sample is duplicated in three studies, all three edges in that graph would have to be shown, meaning there would be three rows to identify the duplication of a single sample.

This spreadsheet can then be made into a documented dataframe in the data/ directory (`DataFrame` would be the Bioconductor way, although we've already gone rogue with a `tbl_df` combined_metadata).

**Comment by paolinomanghi** [comment]
Yes, I'm collecting all the necessities and organising them. Want to avoid
any confusion in the future, and any difficulty in handling the whole
dataset.

**Comment by schifferl** [comment]
This issue was moved to waldronlab/curatedMetagenomicDataCuration#14
