### ISSUE TITLE
spreadsheet

### ISSUE THREAD

**Issue by edoardopasolli** [waldronlab/curatedMetagenomicData#121]
adding the option to download a spreadsheet (simply a .csv) directly from the website?
maybe feasible for metadata + metaphlan_bugs_list only?

**Comment by schifferl** [comment]
@edoardopasolli I agree this would be very useful, and should be provided so the data is useful in other languages (python, stata, etc.)

**Comment by lwaldron** [comment]
Note that the command-line tool can already create `.tsv` files for all available datasets - the main issue here is deciding on a home for them (AWS S3?) and figuring out how to keep them up to date & versioned with new versions of the package.

**Comment by lwaldron** [comment]
Need to decide whether to do this from curatedMetagenomicData or from APIs. The API will have the most up-to-date data, so is probably preferable. This could potentially be endpoints of the API.

**Comment by lwaldron** [comment]
Currently blocked by #165. Example using current package:

```r
library(curatedMetagenomicData)
x <- curatedMetagenomicData("*metaphlan*", dryrun=FALSE)
xmerge <- mergeData(x)

write.csv(exprs(xmerge), file = "metaphlan_bugs_list.csv") #will be assay instead of exprs in cMD3
write.csv(pData(xmerge), file = "metadata.csv") #will be colData instead of pData in cMD3
```

**Comment by lwaldron** [comment]
Put these in a zip file attached to this issue, as well as the code used to produce them using cMD 3.0.

**Comment by sdgamboa** [comment]
@lwaldron 

Output files with curatedMetagenomicData3.0 and the mergeData function #202 :

[relative-abundance_metadata-cMD3.0.zip](https://github.com/waldronlab/curatedMetagenomicData/files/6341883/relative-abundance_metadata-cMD3.0.zip)

Code:

```r
library(curatedMetagenomicData)
library(SummarizedExperiment)
resources <- curatedMetagenomicData(pattern = "relative_abundance", print = FALSE, dryrun = TRUE)
length(resources)
head(resources)
data_sets <- lapply(resources, function(x) curatedMetagenomicData(x, print = FALSE, dryrun = FALSE))
names(data_sets) <- gsub("^.*\\.(.*)\\..*$", "\\1", resources)
merged_data_sets <- mergeData(data_sets)
write.csv(assays(merged_data_sets)$relative_abundance, file = "~/cMD_relative_abundance.csv") # created in home directory
write.csv(colData(merged_data_sets), file = "~/cMD_metadata.csv") # created in home directory
```

**Comment by schifferl** [comment]
This is the territory of the CLI package (https://github.com/waldronlab/curatedMetagenomicDataCLI) now, and is already accomplished there. Closing
