### ISSUE TITLE
How to create metadata.tsv

### ISSUE THREAD

**Issue by zhanxw** [waldronlab/curatedMetagenomicData#128]
I want to create an ExpressionSet by following this [link](https://github.com/waldronlab/curatedMetagenomicData/wiki/The-curatedMetagenomicData-pipelines).
But I don't understand the format requirement for `metadata.tsv`.
I have tried but failed to:

1.  find an example `metadata.tsv` file from `s3://curatedmetagenomics.bioconductor.org
`

> ~> aws s3 ls s3://experimenthub/curatedMetagenomicData/
> 
> An error occurred (AccessDenied) when calling the ListObjects operation: Access Denied
> 
> ~> aws s3 cp s3://experimenthub/curatedMetagenomicData/LomanNJ_2013_Mi.tar.gz  .
> fatal error: An error occurred (403) when calling the HeadObject operation: Forbidden
> 

2. create my own file from the [template](https://github.com/waldronlab/curatedMetagenomicDataCuration/blob/master/inst/extdata/template.csv), but `make_data()` failed:

> > make_data("XXXX/FrankelAE_2017.tar.gz")
> Parsed with column specification:
> cols(
>   col.name = col_character(),
>   var.class = col_character(),
>   uniqueness = col_character(),
>   requiredness = col_character(),
>   multiplevalues = col_logical(),
>   allowedvalues = col_character(),
>   description = col_character()
> )
> Error in -PMID : invalid argument to unary operator

Can you provide instructions on creating a `metadata.tsv` file or show me an example?

**Comment by edoardopasolli** [comment]
The metadata files for all the datasets included in the package can be found from here: https://github.com/waldronlab/curatedMetagenomicDataCuration/tree/master/inst/curated/

**Comment by zhanxw** [comment]
I missed some required columns (e.g. `PMID`). 
All required columns are specified in the template file [link](https://github.com/waldronlab/curatedMetagenomicDataCuration/blob/master/inst/extdata/template.csv).

**Comment by edoardopasolli** [comment]
exactly, all the mandatory fields are marked as "required" in the template.csv file
