### ISSUE TITLE
make_data failed

### ISSUE THREAD

**Issue by zhanxw** [waldronlab/curatedMetagenomicData#129]
I followed the instruction of curatedMetagenomicData pipelin [link](https://github.com/waldronlab/curatedMetagenomicData/wiki/The-curatedMetagenomicData-pipelines), but failed with a warning related to `full_join`.
From this line [link](https://github.com/waldronlab/curatedMetagenomicDataPipeline/blob/01b484c6414d82495a7dd2be6ec8489d68b31ddf/R/combine_metadata.R#L7), the variable `combined_metadata` is a DataFrame and it cannot be parsed to `full_join`.  Is it a bug? I am attempting to replace it with `combined_metadata <- full_join(as.data.frame(combined_metadata), metadata)`.

> > make_data("MyData.tar.gz")
> Parsed with column specification:
> cols(
>   col.name = col_character(),
>   var.class = col_character(),
>   uniqueness = col_character(),
>   requiredness = col_character(),
>   multiplevalues = col_logical(),
>   allowedvalues = col_character(),
>   description = col_character()
> )
> |=================================================================| 100%   22 MB
> |=================================================================| 100%   25 MB
> |=================================================================| 100%   25 MB
> |=================================================================| 100%   17 MB
> |=================================================================| 100%   20 MB
> |=================================================================| 100%   20 MB
> |=================================================================| 100%   28 MB
> |=================================================================| 100%   23 MB
> |=================================================================| 100%   20 MB
> |=================================================================| 100%   26 MB
> |=================================================================| 100%   21 MB
> |=================================================================| 100%   19 MB
> Error in UseMethod("full_join") :
>   no applicable method for 'full_join' applied to an object of class "c('DataFrame', 'DataTable', 'SimpleList', 'DataTableORNULL', 'List', 'Vector', 'Annotated')"
> In addition: Warning messages:
> 1: In function_list[[i]](value) : NAs introduced by coercion
> 2: In pubmed_check(.) :
>   No pubmedids were found and ExperimentData will reflect this

**Comment by schifferl** [comment]
Hi @zhanxw, this error occurred because of the transition I made from `data.frame` objects to `DataFrame` objects in the last release. I will get the issue fixed next week and let you know as soon as I have a patch ready.

**Comment by lwaldron** [comment]
@zhanxw I'm sorry I neglected to update this issue in a timely manner, but I did fix this back on July 5 with commit 2aa0218cd78af2397e3d95683b6f67ecc5d22ffc. I hope it didn't hold you up.
