### ISSUE TITLE
Add getSampleIds function and getData function

### ISSUE THREAD

**Issue by DryLab-Scientific** [waldronlab/curatedMetagenomicData#134]
getSampleIds <- function(filterstring="gender=='male' & disease=='CRC'"){
  filterstring <- parse(text = filterstring)
  unnested <- dplyr::mutate(data.frame(combined_metadata), disease=strsplit(disease, ";")) %>% 
    tidyr::unnest(disease) %>%
    mutate(antibiotics_family=strsplit(antibiotics_family, ";")) %>%
    tidyr::unnest(antibiotics_family)
  unnested <- base::subset(unnested, base::eval(filterstring))
  return(dplyr::select(unnested, dataset_name:sampleID))
}

getAllData <- function(sampleids, datatype="metaphlan_bugs_list"){
  datasets <- unique(sampleids$dataset_name)
  string <- paste(datasets, datatype, sep=".")
  string <- paste0(string, ".+")
  string <- paste0(string, collapse="|")
  res <- curatedMetagenomicData(string, x.is.glob = FALSE, dryrun = FALSE)
  mergeData(res)
}

Previous function is as above. getAllData is not correct, which should take getSampleIds result as input.

**Comment by lwaldron** [comment]
This is part of #130 .
