### ISSUE TITLE
make_data() does not version datasets

### ISSUE THREAD

**Issue by lwaldron** [waldronlab/curatedMetagenomicData#140]
No dates are prepended to the filenames or the Title column in `inst/extdata/metadata.csv`. Presumably `add_version_number()` needs to be called as an additional (undocumented) step. 

However, after running `make_data()` on all datasets, we will end up with repeated entries in ExperimentHub, with a new version the same as the old version. @schifferl how this is supposed to work?

**Comment by lwaldron** [comment]
Possible fix in version-to-make_data() branch:

https://github.com/waldronlab/curatedMetagenomicData/tree/version-to-make_data()

**Comment by cmirzayi** [comment]
Yeah it appears that it's in `make_all()` but was not documented in the Wiki. I added instructions to the Wiki to run `add_version_number()` after running `make_data()` for all the datasets. Also as the Wiki is getting long and it might be easy to miss a step or two I added a "tl;dr" at the end with a bare bones step-by-step list of steps for running the pipeline.
