### ISSUE TITLE
Deprecation process for munged dataset names

### ISSUE THREAD

**Issue by lwaldron** [waldronlab/curatedMetagenomicData#149]
The next step is to change Deprecated -> Defunct in the master branch here in GitHub and on git.bioconductor.org. Not a rush but should be done soon.

[Current matches of "deprecated"](https://github.com/waldronlab/curatedMetagenomicData/search?q=deprecated&unscoped_q=deprecated)

[Bioconductor deprecation HOWTO](https://bioconductor.org/developers/how-to/deprecation/)

After the release of Bioconductor 3.10 in April 2019, the final step will be to:

- [ ] Remove all reference to defunct functions in the master branch

**Comment by lwaldron** [comment]
@cmirzayi can you close this issue?

**Comment by cmirzayi** [comment]
The issue was resolved as of the April release.
