### ISSUE TITLE
MetaPhlAn2 and HUMANn2 profiles of two new Italian cohorts of CRC

### ISSUE THREAD

**Issue by yiqijiang17** [waldronlab/curatedMetagenomicData#154]
Hi all,
In the Data Availability part of "Metagenomic analysis of colorectal cancer datasets
identifies cross-cohort microbial diagnostic
signatures and a link with choline degradation" mentioned,

> Nucleotide sequences for the two new Italian cohorts are available in the Sequence
Read Archive under accession No. SRP136711. MetaPhlAn2 and HUMANn2
profiles for the new cohorts were also added to the curatedMetagenomicData
R package along with their corresponding metadata.

The two new cohorts, one contains 80 samples, another contains 60 samples based on the manuscript method. I find the 80 samples one is ThomasAM_2018a in curatedMetagenomicData v1.21.3, but still have no idea about which one is the 60 samples cohort. 
And the data in "http://waldronlab.io/curatedMetagenomicData/datasets-included/" didn't contains such record.
Could you help me with that?
Thanks a lot.

**Comment by nsegata** [comment]
Hi, we are still updating the package, but Paolo (in CC) can provide the
tables that are not already in cMD.

thanks
Nicola

**Comment by paolinomanghi** [comment]
Hi, thanks for getting in touch. The table for the new cohorts are available via Dropbox, at "http://segatalab.cibio.unitn.it/data/Thomas_et_al.html". We will add all the data for the described meta-analysis soon, encompassing all the cohorts and all the profile types

**Comment by edoardopasolli** [comment]
The two datasets have been added as ThomasAM_2018a and ThomasAM_2018a. I close this issue.
