### ISSUE TITLE
Importing metaphlan2/HUMAnN2 output tables into curatedMetagenomicData

### ISSUE THREAD

**Issue by fconstancias** [waldronlab/curatedMetagenomicData#155]
Hi,
I am trying to import metaphlan2/HUMAnN2 output I have generated into cureatedMetagenomicData. Do you have any guidelines - tutorial ?

Thanks a ton

**Comment by edoardopasolli** [comment]
Hi,

We are happy to include your dataset into the package.
Are the raw reads already publicly available? In that case we can simply process and include them. If not, let us know and we'll see how to proceed to move the files.

Thanks,
Edoardo

**Comment by fconstancias** [comment]
Thank you for your answer.
The raw data are not available yet, I am actually working on the functional and taxonomic tables produced but metaphlan2/humann2 and the idea is to import those tables as a curatedMetagenomicData R object in order to put my dataset in the context of already published dataset available in curatedMetagenomicData.

**Comment by edoardopasolli** [comment]
You should follow these instructions to upload the profiles: https://github.com/waldronlab/curatedMetagenomicData/wiki/The-curatedMetagenomicData-pipelines

Let us know if you have any issues!

**Comment by fconstancias** [comment]
Thanks for your help.
I run metaphlan2 and then humann2 specifiing the metaphlan2 bug list.
I have .tsv tables for pathcoverage, pathabundance and gene_families. I did normalize the two latter to relative abundance. But I am a bit confused with the marker_abundance and marker_presence tables I should also upload. It sounds to me that they are related to metaphlan2 output but I have just kept *profile.bowtie2.bz2, *profile.txt and *profile.bowtie2.sam.bz2 as metaphlan2 output.

Could you clarify were to get the marker_abundance and marker_presence tables?

**Comment by fconstancias** [comment]
any update? Thanks for your help

**Comment by lwaldron** [comment]
Sorry your commen fell off our radar @fconstancias. Those were produced by the run_markers2.py file at https://github.com/waldronlab/curatedMetagenomicDataHighLoad/tree/master/docker/curatedMetagenomics. However we're completely reworking the pipeline while upgrading to humann3 and metaphlan3 - one step of that that's ready already is the Docker container in that directory with those and sratoolkit installed. But run_markers2.py needs to be updated, which @fbeghini can comment on. The .sh script will also be updated.

**Comment by fconstancias** [comment]
Thanks a lot for the update @lwaldron. Can't wait to process my data with metaphlan3/humann3/curatedMetagenomicData !

**Comment by fbeghini** [comment]
HI @fconstancias , both the run_markers2.py and the .sh script are updated and MetaPhlAn 3 capable!

**Comment by lwaldron** [comment]
Where are these updates @fbeghini?

**Comment by fbeghini** [comment]
Sorry, forgot to push the commits, now are available

**Comment by lwaldron** [comment]
Thanks @fbeghini! @fconstancias, note the `.sh` script still isn't ready for use as-is but we're working on it (https://github.com/waldronlab/curatedMetagenomicDataHighLoad/issues/15)

**Comment by fconstancias** [comment]
@lwaldron good to know thanks. @fbeghini, any idea when you guys plan to released humann3?

**Comment by fbeghini** [comment]
@fconstancias An alpha version of 3.0 is available [here](https://github.com/biobakery/humann/blob/3.0.0-alpha-rename) and also on pypi (pip install human) and biobakery conda channel (conda install -c biobakery human)

**Comment by lwaldron** [comment]
@fconstancias FYI I've made a Docker image with humann3.0.0-alpha and metaphlan3, along with SRA toolkit ([waldronlab/curatedmetagenomics](https://hub.docker.com/repository/docker/waldronlab/curatedmetagenomics)). You could use Bulker.io following [these instructions](https://github.com/waldronlab/bioconductor/wiki/Running-Bioconductor-in-Docker-using-Bulker) if you wanted to abstract away the Docker container and use Biobakery programs from the command line as they were installed locally.

**Comment by charlottecc** [comment]
Hi, 
I'm quite new to metagnomics and R, but I was wondering if you could offer me some advice. 
After seeing the metaphlantophyloseq function which I think uses this package. I have converted my metaphlan3 relative abundance output into phyloseq objects with the hope of inputting these into Deseq2. Is it right to have done this because the metaphlan output is relative abundance and not raw counts? Does curatedmetagenomics allow you to somehow convert the relative abundance for further analysis? 

Thank you in advance for any help!

**Comment by fconstancias** [comment]
Hi @charlottecc ,

You could normalize species proportion with reads counts prior running Deseq analysis or alpha-diversity analysis within phyloseq environment for instance. See Estimating Absolute Raw Count Data from [here](https://rstudio-pubs-static.s3.amazonaws.com/231941_e6841f25c018408385ecfc72200724bc.html.)

@lwaldron, were you able to update the scripts to import metphlan humman generated data (v3) into curatedMetagenomicData?
