### ISSUE TITLE
Annotations for gene families

### ISSUE THREAD

**Issue by b-tierney** [waldronlab/curatedMetagenomicData#160]
Hi,

I have a number of Uniref90 IDs pulled from CMD that are out of date with the current Uniref, meaning I can't look up what the annotations are. I could grab them from Uniparc, but doing so by hand isn't feasible for the thousands of IDs I need to query. 

Can you recommend a way to map Uniref90 IDs from the gene family datasets to gene names? Or at the very least, is there sequence information somewhere?

I know this might be a HUMAnN2 issue at its core, if it were run on a past version of Uniref. Do you happen to have that versioning info somewhere? Or the gene database in question?

Thanks,
Braden

**Comment by edoardopasolli** [comment]
Hi Braden,

I don't have a solution for updating the entries to current UniRef/UniProt identifiers, and it is something not implemented in curatedMetagenomicData.

But anything UniRef that was profiled by HUMAnN2 could be named/regrouped with current annotations using the HUMAnN2 rename/regroup utilities and utility mapping files. Please check out these sections of the manual for more details:
https://bitbucket.org/biobakery/humann2/wiki/Home#markdown-header-humann2_regroup_table
https://bitbucket.org/biobakery/humann2/wiki/Home#markdown-header-humann2_rename_table

**Comment by b-tierney** [comment]
Got it, thank you for the quick response. It looks like the rename table may get at what I'm going for, provided that mapping file (map_uniref90_name.txt) has each Uniref90 ID ever used in a HUMAnN2 database. Is that the case?

That said, do you happen to have recorded the version of HUMAnN2 you used for processing each dataset in CMD? I'd love to have the raw sequences for my consensus genes, and the only way I can think to get them is via mapping HUMAnN2 version to Uniref90 DB version...which I assume will be possible, if only by matching up release dates of the two.

**Comment by edoardopasolli** [comment]
Each dataset in cMD was processed with HUMAnN2 v0.7.1

**Comment by b-tierney** [comment]
Thanks. I ended up figuring out that the characters following "Uniref90_" for each gene name are deprecated UniprotKB IDs that map to Uniparc IDs which, in turn, can be used to map to current Uniref90. Probably wouldn't be too hard to build global mapping files from the Uniprot site if need be.

Thanks again for the help! I'm very grateful for your quick responses and this amazing resource.
