### ISSUE TITLE
Some data sets are missing

### ISSUE THREAD

**Issue by lsayaved** [waldronlab/curatedMetagenomicData#161]
Hi!, 
Some datasets are not available even though there are MAGS assembled from these data sets. Specifically, I am referring to: HeQ_2017 and WenC_2017. Were these data sets renames?
Thanks!

**Comment by edoardopasolli** [comment]
Hi,

Are you referring to the MAGs present in the Cell paper? "Extensive Unexplored Human Microbiome Diversity Revealed by Over 150,000 Genomes from Metagenomes Spanning Age, Geography, and Lifestyle"

We didn't find the complete metadata information for HeQ_2017 and WenC_2017, so these two datasets are currently not included in curatedMetagenomicData.
But I can tell you that all the samples are from stool, adults, china. This is reported in the Supplementary Table 1, Tab2 of the above mentioned paper.
