### ISSUE TITLE
Document assemblies used

### ISSUE THREAD

**Issue by solna86** [waldronlab/curatedMetagenomicData#164]
Thanks for this package. A curated & standardized resource is tremendously helpful.

Excuse my ignorance, but I couldn't find any pointer that links to the assembly you are using to quantify all datasets. As far as I understand, you use MetaPhlAn 2.0 (or already transitioned to 3.0?). By looking into MetaPhlAn 2.0 docs, and the source of curatedMetagenomicData I couldn't find that information either.

I would like to look into the particular genomes of a few species that are differentially expressed in a dataset included in your package, so this would be really helpful.

**Comment by edoardopasolli** [comment]
Thanks for appreciating our resource!

Yes current profiles were generated with MetaPhlAn 2.0 (we will transition to 3.0 soon).
Please find attached the taxa that were used in MetaPhlAn 2.0, the last code is the NCBI assembly ID
[all.tax.txt](https://github.com/waldronlab/curatedMetagenomicData/files/4747155/all.tax.txt)

**Comment by solna86** [comment]
Thanks for the quick response.

I am closing the issue, as this answered my question.

It would be great to get everything updated to MetaPhlAn 3.0 and perhaps a newer assembly such as the excellent one from your Cell paper:

http://segatalab.cibio.unitn.it/data/Pasolli_et_al.html
