### ISSUE TITLE
MetaPhlan3 and HUMAnN3

### ISSUE THREAD

**Issue by ruairirobertson** [waldronlab/curatedMetagenomicData#165]
Hi there!

Thanks for an excellent package! I am wondering if there are plans to update the curatedMetagenomicData to include output from the recent versions 3 of MetaPhlan and HUMAnN? It would be great to have this updated output!

Thanks!

**Comment by lwaldron** [comment]
It is coming! We're trying to get this in time for this month's Bioconductor release, but if not it will be in devel not long after. We'll post an update here.

**Comment by ruairirobertson** [comment]
Thanks for your quick reply! Looking forward to using the next release. It will be great to use the new HMP data from the TEDDY study etc, I see they are on your list of datasets to include!

**Comment by paolinomanghi** [comment]
Hi Ruairi,
thanks for getting in touch.
We are ready to include the HMP_2019 IBD and type-2 diabetes cohorts
(authors: Loyd-Price & Zhou). As far as I know I still haven't included the
TEDDY cohort.
Does this make sense to you?

Bests,
Paolo

**Comment by ruairirobertson** [comment]
Great, thanks! Ah yes no problem, I was referring to Stewart et al and Vatanen et al for the TEDDY cohort. Will these be added later?

**Comment by paolinomanghi** [comment]
Ah ok, the Vatanen 2019 is ready too: I can work directly on the TEDDYs,
indeed!

**Comment by lwaldron** [comment]
@cmirzayi can you list here in general the issues preventing processing the new cMD tarballs? Then you could also open specific issues as separate issues on the tracker. FYI also @jwokaty @schifferl

**Comment by cmirzayi** [comment]
Sure the general issues that I am aware of are:

1. Significant memory usage during the `make_data()` step due to a `dplyr::full_join()`
2. Accommodating the 4th column in MetaPhlan3 profiles

I will open specific issues with more information for each of these.

**Comment by lwaldron** [comment]
@cmirzayi will you post your download + build code here?

**Comment by cmirzayi** [comment]
Yes it's very straight-forward.

```
#Testing importing and processing new cMD datasets from a google cloud bucket

#fetch required packages and functions for cMD
library(dplyr)
source("./inst/scripts/make-data.R")

#copy tarball from gcs
library(AnVIL)
gsutil_cp("gs://cmdstorage/AsnicarF_2017.tar.gz", "AsnicarF_2017.tar.gz")

#run cMD pipeline
make_data("AsnicarF_2017.tar.gz")
add_version_number()
make_data_documentation()
make_metadata()
make_upload()

```

**Comment by lwaldron** [comment]
This will be the "main" issue to link several other related issues to, to be closed when curatedMetagenomicData 3 enters bioc-devel. See https://github.com/waldronlab/curatedMetagenomicData/tree/remodel branch.

**Comment by schifferl** [comment]
This issue can be closed but I hesitate to do it myself, please have a look @lwaldron and close it if you are satisfied that the data are now in ExperimentHub and are returned as SummarizedExperiment objects with the package installed from GitHub. I prefer to close it ASAP, rather than waiting for cMD v 3.0.0 to enter release.

**Comment by lwaldron** [comment]
Let's replace the "milestone" function of this issue with an the GitHub Milestone feature for what needs to be completed for the Bioconductor 3.13 release. That has has advantages of deadlines and progress tracking: https://github.com/waldronlab/curatedMetagenomicData/milestones
