### ISSUE TITLE
Study inclusion request

### ISSUE THREAD

**Issue by jboktor** [waldronlab/curatedMetagenomicData#166]
Hello, 

I'd like to request the addition of the following study on Parkinson's Disease:
Paper link: https://doi.org/10.1093/brain/awaa201
BioProject: PRJNA433459

**Comment by edoardopasolli** [comment]
Thanks for your request, I added it to the list of datasets to process.
We are making a major update of the package and we are not able to add new datasets in the short time, but we'll do when possible
