### ISSUE TITLE
Significant memory usage due to join_assays()

### ISSUE THREAD

**Issue by cmirzayi** [waldronlab/curatedMetagenomicData#167]
I have attempted processing two datasets (OhJ_2014, 368.2 MB; NagySzakalD_2017, 529 MB) on both a computer (32 GB of ram) and Terra cloud environment (~110 GB of ram). On my computer, both datasets failed at the same step due to running out of available memory. This function is `join_assays()` as part of the `assay_merge()` function:

```
assay_merge <- function(tsv_list) {
    lapply(tsv_list, read_assay) %>%
    Reduce(join_assays, .) %>%
    as.data.frame()
}
```

```
join_assays <- function(first_assay, second_assay) {
    full_join(first_assay, second_assay, by = "rownames")
}
```

@lwaldron recommended replacing `join_assays()` with `joinListOfMatrices()` which should be faster and more memory-efficient.

**Comment by lwaldron** [comment]
Example using joinListofMatrices:
```r
library(curatedMetagenomicData)
example("matrix")
mdat2 <- mdat
rownames(mdat2)[2] <- "row3"
colnames(mdat2) <- paste0("new", colnames(mdat2))

listofmat <- list(mdat, mdat2)
curatedMetagenomicData:::joinListOfMatrices(listofmat, NULL)
```

**Comment by lwaldron** [comment]
Part of #165, resolved eventually at https://github.com/schifferl/curatedmetagenomicdatapipeline

**Comment by lwaldron** [comment]
Now resolved at https://github.com/schifferl/curatedmetagenomicdatapipeline
