### ISSUE TITLE
cMD3 taxonomy names

### ISSUE THREAD

**Issue by lwaldron** [waldronlab/curatedMetagenomicData#169]
Need to account for new naming in metaphlan3.  Ideally keep the NCBI IDs in rowData, but this is not critical because we can provide a map separately.

**Comment by lwaldron** [comment]
Examples at https://storage.cloud.google.com/data-curatedmetagenomics. E.g. 

* small: https://storage.googleapis.com/data-curatedmetagenomics/AsnicarF_2017.tar.gz
* big: https://storage.googleapis.com/data-curatedmetagenomics/AsnicarF_2021.tar.gz

New simplified function for reading files and creating list of matrices: https://github.com/schifferl/curatedmetagenomicdatapipeline

**Comment by lwaldron** [comment]
See https://github.com/waldronlab/curatedMetagenomicData/tree/remodel branch

**Comment by schifferl** [comment]
The NCBI Taxonomy IDs were removed from the the tsv inputs, but could be mapped again. I am closing this for now because it would rather be a feature request.

**Comment by lwaldron** [comment]
Dropping the NCBI IDs is a significant loss of annotation that makes it more difficult to find taxa or do microbe set analysis, making it a high priority and an open feature request, but not critical to the cMD 3.0 release. If you prefer I'll post it as a separate feature request though.
