### ISSUE TITLE
use a sparse matrix representation for stratified genefamilies_relab

### ISSUE THREAD

**Issue by lwaldron** [waldronlab/curatedMetagenomicData#170]
If practical - this is not critical.

**Comment by lwaldron** [comment]
Add an argument to [joinListofMatrices](https://github.com/waldronlab/curatedMetagenomicData/blob/8097b8ad45adbdbd9425c8d5b4d8ea05da8f494e/R/mergeData.R#L54) function to create [output](https://github.com/waldronlab/curatedMetagenomicData/blob/8097b8ad45adbdbd9425c8d5b4d8ea05da8f494e/R/mergeData.R#L67) as a Matrix::dgTMatrix class matrix.

**Comment by schifferl** [comment]
Just wanted to give an update on this, a `ExpressionSet` won't handle sparse matrices – so this would have to be coupled with an update to `SummarizedExperiment`. Will leave this alone for now.

**Comment by lwaldron** [comment]
See https://github.com/waldronlab/curatedMetagenomicData/tree/remodel branch

**Comment by lwaldron** [comment]
Part of #165
