### ISSUE TITLE
MetaPhlAn3 Newick tree

### ISSUE THREAD

**Issue by lwaldron** [waldronlab/curatedMetagenomicData#176]
Need to add the MetaPhlAn3 Newick tree to inst/extdata (e.g. https://github.com/waldronlab/curatedMetagenomicData/blob/master/inst/extdata/metaphlan2_selected.tree.reroot.nwk.bz2). Related to #165

**Comment by paolinomanghi** [comment]
Pushed mpa_v30_CHOCOPhlAn_201901_species_tree.nwk.bz2 MetaPhlAn3 Newik tree to inst/extdata/
