### ISSUE TITLE
Create GHA to build package

### ISSUE THREAD

**Issue by jwokaty** [waldronlab/curatedMetagenomicData#178]
Create a GitHub Action to use biocthis and run

* BiocCheck::BiocCheck()
* R CMD Check

**Comment by jwokaty** [comment]
@lwaldron Should I also remove [.travis.yml](https://github.com/waldronlab/curatedMetagenomicData/blob/master/.travis.yml) since we're no longer using Travis?

**Comment by lwaldron** [comment]
yes--

Levi Waldron

Associate Professor

Department of Epidemiology and Biostatistics

CUNY Graduate School of Public Health and Health Policy

Institute for Implementation Science in Population Health

55 W 125th St, New York NY 10035

https://waldronlab.io
