### ISSUE TITLE
Change combined_metadata.rda GHA to use r-devel

### ISSUE THREAD

**Issue by jwokaty** [waldronlab/curatedMetagenomicData#179]
Change GHA to update combined_metadata.rda to use r-devel. See https://github.com/waldronlab/curatedMetagenomicData/runs/2154047902?check_suite_focus=true#step:3:3.

**Comment by lwaldron** [comment]
Agreed, good idea.

**Comment by lwaldron** [comment]
Although, note that bioc-devel uses r-release for half the year (http://bioconductor.org/developers/how-to/useDevel/), so for Bioconductor packages it's better to use the Bioconductor Docker images. But this isn't, so actually I think you can use whichever R version you want / that works.
