### ISSUE TITLE
dataset documentation 3 - enrich documentation

### ISSUE THREAD

**Issue by lwaldron** [waldronlab/curatedMetagenomicData#18]
Most of the useful per-dataset documentation has been lost in the new pipeline.  Restore the more helpful documentation provided by the old pipeline, for example this [Candela_Africa.stool.eset.Rd](https://github.com/vobencha/curatedMetagenomicData/blob/397fe7b75397d2170b2759f4b1509e9be3bac59a/man/Candela_Africa.stool.eset.Rd).

**Comment by lwaldron** [comment]
This doesn't seem like it should be hard because I wrote a script for it, or is it?

**Comment by lwaldron** [comment]
Although this should be done along with Issue #17 or else the manual would be voluminous.

**Comment by lwaldron** [comment]
Attaching a richer manual based on a previous version for demonstration purposes.

[curatedMetagenomicData-397fe7b75397d2170b2759f4b1509e9be3bac59a.pdf](https://github.com/vobencha/curatedMetagenomicData/files/624892/curatedMetagenomicData-397fe7b75397d2170b2759f4b1509e9be3bac59a.pdf)

**Comment by schifferl** [comment]
![bitmoji](https://render.bitstrips.com/v2/cpanel/10161328-196657087_9-s4-v1.png?transparent=1&palette=1&width=246)

Working on this and will have it done shortly!

**Comment by schifferl** [comment]
Closed by f535e99e53099ed03b0914f1e36c59b7cdb20ebb, simply github install the package to see the more informative and condensed documentation

**Comment by lwaldron** [comment]
The new descriptives plots in RStudio man pages are neat, but because they don't show up in the PDF manual or in the console, I would suggest they should supplement, rather than replace, frequency tables. Having ctrl-F in the PDF manual is handy. And/or, add a table to the vignette that summarizes over all datasets.

**Comment by schifferl** [comment]
Examples of new and old documentation
[R- Data from the Obregon_TitoAJ_2015 study - New.pdf](https://github.com/waldronlab/curatedMetagenomicData/files/1049128/R-.Data.from.the.Obregon_TitoAJ_2015.study.-.New.pdf)
[R- Data from the Obregon_TitoAJ_2015 study - Old.pdf](https://github.com/waldronlab/curatedMetagenomicData/files/1049129/R-.Data.from.the.Obregon_TitoAJ_2015.study.-.Old.pdf)

**Comment by schifferl** [comment]
I will work to add the frequency table and figures to both HTML and PDF documentation.

**Comment by lwaldron** [comment]
We'll no longer have dataset-specific man pages, datasets will be documented in a (possibly separate) vignette.
