### ISSUE TITLE
incorporate Newick tree

### ISSUE THREAD

**Issue by lwaldron** [waldronlab/curatedMetagenomicData#188]
Some options:
1. Put it in metadata(SE)
2. Use TreeSummarizedExperiment
3. Only use it for the phyloseq conversion

See https://github.com/waldronlab/curatedMetagenomicData/blob/master/inst/legacy/mpa_v30_CHOCOPhlAn_201901_species_tree.nwk.bz2 (should be added into cMD 3 too)

**Comment by schifferl** [comment]
This will be solved by strategy # 2, and is at the top of the docket. I am working by Trello cards more than issues right now, so I will close the issue and close #206 because they will be resolved with the `TreeSummarizedExperiment` change. See https://trello.com/c/bU0kGfm2
