### ISSUE TITLE
migrate ExpressionSet2phyloseq to remodel

### ISSUE THREAD

**Issue by lwaldron** [waldronlab/curatedMetagenomicData#190]
See https://github.com/waldronlab/curatedMetagenomicData/blob/legacy/man/ExpressionSet2phyloseq.Rd

- [ ] Get rid of long-name function call `LomanNJ_2013.metaphlan_bugs_list.stool()`
- [x] replace `ExpressionSet2phyloseq` function (will no longer be using ExpressionSet objects)
- [x] Replace references to ExpressionSet with references to SummarizedExperiment
- [x] It's confusing to offer both `relab = TRUE/FALSE` and `counts = TRUE/FALSE` argument to curatedMetagenomicData(). Add an error if `relab` argument is specified, saying to use the counts argument instead (I think this can be done using defunct functionality?)  Also eliminate the vignette section recommending this use of ExpressionSet2phyloseq().

**Comment by lwaldron** [comment]
Do along with issue #92

**Comment by sdgamboa** [comment]
@lwaldron I'm changing the name of the function and the R file to SummarizedExperiment2phyloseq(.R).

+ Should the ExrpessionSet2phyloseq.R file still be included in the package as a defunct function?

+ Is the `count = TRUE` argument still wanted in the new `SummarizedExperiment2phyloseq` function? I think this option is now used upstream in the workflow when the user calls the `curatedMetagenonicData` function. So my thinking is that the user should get a SummarizedExperiment-class object with counts (or not) before using the `SummarizedExperiment2phyloseq` function.

Example: 
```r
# Example 1 - With counts
AsnicarF2021se_counts <- curatedMetgenomicData("AsnicarF_2021.relative_abundance",  dryrun = FALSE, counts = TRUE)
pseq_counts <- SummarizedExperiment2phyloseq(AsnicarF2021se_counts,  phylogenetictree = TRUE)

# Example 2 - Without counts
AsnicarF2021se <- curatedMetgenomicData("AsnicarF_2021.relative_abundance",  dryrun = FALSE)
pseq <- SummarizedExperiment2phyloseq(AsnicarF2021se,  phylogenetictree = TRUE)

```

**Comment by lwaldron** [comment]
You're right @sdgamboa - with the counts argument in the curatedMetagenomicData function, it's not needed here.

**Comment by schifferl** [comment]
This issue is replaced by #225 and will now be closed.
