### ISSUE TITLE
restore unit tests for cMD 3.0

### ISSUE THREAD

**Issue by lwaldron** [waldronlab/curatedMetagenomicData#192]

**Comment by jwokaty** [comment]
I think the only test to restore (and fix) are

* https://github.com/waldronlab/curatedMetagenomicData/blob/46852cae6cf21324b9104e39f8cd820f970ac455/tests/testthat/test-mergeData.R
* https://github.com/waldronlab/curatedMetagenomicData/blob/46852cae6cf21324b9104e39f8cd820f970ac455/tests/testthat/test-curatedMetagenomicData.R
* https://github.com/waldronlab/curatedMetagenomicData/blob/46852cae6cf21324b9104e39f8cd820f970ac455/tests/testthat/test-ExpressionSet2phyloseq.R but this should become SummarizedExperiment2phyloseq.R
* https://github.com/waldronlab/curatedMetagenomicData/blob/46852cae6cf21324b9104e39f8cd820f970ac455/tests/testthat/test-ExpressionSet2MRexperiment.R (might change depending how implemented in #193)

Maybe there should also be tests for R/getMetaphlanTree.R if #194 is implemented.

Anything missing here?

**Comment by lwaldron** [comment]
Looks far as I can remember. @schifferl?

**Comment by jwokaty** [comment]
@schifferl There's overlap between this issue and #219. Would you prefer to close this issue?

**Comment by schifferl** [comment]
Thank you @jwokaty, yes, I am going to close this issue and we can keep the discussion going on #219.
