### ISSUE TITLE
migrate ExpressionSet2MRexperiment.R to remodel

### ISSUE THREAD

**Issue by lwaldron** [waldronlab/curatedMetagenomicData#193]
See https://github.com/waldronlab/curatedMetagenomicData/tree/legacy/R

- [ ] Get rid of long-name function call `LomanNJ_2013.metaphlan_bugs_list.stool()`
- [ ] replace `ExpressionSet2MRexperiment` function (will no longer be using ExpressionSet objects)
- [ ] Replace references to ExpressionSet with references to SummarizedExperiment

**Comment by schifferl** [comment]
This issue is replaced by #224 and will now be closed.
