### ISSUE TITLE
Make a dataset-documentation vignette

### ISSUE THREAD

**Issue by lwaldron** [waldronlab/curatedMetagenomicData#198]
Complementary to the main vignette #65. Use the `combined_metadata` object and e.g. `kable` package to create a big table of the datasets and their properties (# samples, body site, diseases, age, other metadata available).

**Comment by lwaldron** [comment]
Added in 3d010957f1a41b9c4fc1ffbd15c981c8ee18aa9c, but could use some decoration:
- [ ] diseases
- [ ] body_site
- [ ] body_subsite
- [ ] PMID as a hyperlink to PubMed

**Comment by schifferl** [comment]
The first three were added in edad5cd, but the table looks messy now (https://waldronlab.io/curatedMetagenomicData/articles/articles/available-studies.html). I would opt for just the Study, PMID, Curator, and Samples columns. As for the hyperlink, I can't seem to get around the HTML escaping that goes on inside pkgdown. I'll close this for now and the PMID as a hyperlink will become a feature request on the Trello board.
