### ISSUE TITLE
add method for sample-level returns

### ISSUE THREAD

**Issue by schifferl** [waldronlab/curatedMetagenomicData#216]
**Is your feature request related to a problem? Please describe.**
Often in is desirable to return multiple studies merged together and filtered by some sample metadata criteria (e.g. `age >= 65`). A method to do this with a single method call currently does not exist in curatedMetagenomicData, but is likely (in my humble opinion) the feature most frequently implemented by users. It would allow for the comparison of samples in mega and meta analyses.

**Describe the solution you'd like**
If implemented this method would provide an interface similar to the `curatedMetagenomicData` method and allow for specification of data type (e.g. `gene_families`) and sample metadata conditions, as aforementioned. It might take unlimited conditions by the `...` argument and check them (logical `&` for multiple) before proceeding to downloading. To my mind the method would be named `selectWhere` in the spirit of SQL `SELECT * FROM table WHERE condition` syntax.

**Describe alternatives you've considered**
With the current API changes this is not so difficult to implement as a user, the process would be approximately as follows.

- Filter the `sampleMetadata` table based on specified conditions
- Pull the unique `dataset_names` from the table and paste `.gene_families` (or another data type) onto them
- Download the studies using the `curatedMetagenomicData` method
- Merge the studies using the `mergeData` method
- Filter the rows of the `TreeSummarizedExperiment` or `SummarizedExperiment` to equal the `sampleID` column of the `sampleMetadata` subset in the first step

**Additional context**
Having written the steps, it seems that they probably should be implemented (because they are common) and those are approximately the instructions. This issue replaces #130 which will be closed now.

**Comment by lwaldron** [comment]
It's a great idea. A downside of the current infrastructure is that users will still have to download an entire study to get one sample from it, but this is a minor concern for most uses. The API client (initial skeleton at https://github.com/waldronlab/metagenomicsClientR) will provide individual-sample downloads, but on the other hand that takes more computation on the user's end for a large dataset. In short, your proposal for implementation seems lightweight and convenient.

**Comment by schifferl** [comment]
Per the meeting today, I'd like you to write a draft of this @jwokaty if you're up to it. This can be implemented one of two ways.

Option one:
```r
dplyr::filter(sampleMetadata, age >= 65) %>%
    selectWhere(dataType = "gene_families")
```

Option two:
```r
selectWhere(dataType = "gene_families", age >= 65)
```

Either way would be ok, the first would need a better name; and, the second just encapsulates the filtering step in the method. Perhaps the first is better because it wouldn't get so ugly with many conditions. Let me know when you're ready and we can review the code.
