### ISSUE TITLE
finish package files

### ISSUE THREAD

**Issue by schifferl** [waldronlab/curatedMetagenomicData#217]
There are a number of files in the package that need attention and are essential to the coming cMD 3.0.0 release. What follows is a list of the files that need attention with a person suggested to work on them in parentheses. Please let me know where to switch names around (or remove them), if I've gotten it wrong. Below the list of files is a description of each and what needs to be done, we can check files off the list when they're ready.

- [x] `DESCRIPTION` (@jwokaty)
- [x] `README.Rmd` (@schifferl)
- [x] `NEWS.md` (@lwaldron)
- [x] `data-raw/phylogeneticTree.R` (@sdgamboa)
- [x] `inst/scripts/make-data.R` (@schifferl)
- [x] `R/curatedMetagenomicData.R` (@schifferl)

**DESCRIPTION**
The main package `Description` field needs to be rewritten to sufficient length to suppress a `BiocCheck` note that says its too short (the reason I put filler text). Contributors, specifically you @jwokaty, need to be added to the `Authors@R` field.

**README.Rmd**
The `README.Rmd` which becomes the GitHub README.md and `Getting Started` page of the pkgdown site needs to be expanded upon with additional text and an explanation of what the package is. More informative examples and even a figure might be helpful to guide new users.

**NEWS.md**
The `NEWS.md` file needs to be prepared for the upcoming release, as it might be the very first time current users are introduced to API changes and the fact that the number of samples in the package has doubled. Formatting should also be check to ensure it will be published at release time.

**data-raw/phylogeneticTree.R**
This file is described by its own issue, see #213.

**inst/scripts/make-data.R**
This file should be a textual description of how the package works and all the components that go into delivering the end result to the user; perhaps this could just be a link to the "Our Pipeline" article on the pkgdown site. In either case, one or both of the files will need to be written to inform users about where data come from.

**R/curatedMetagenomicData.R**
This file is described by its own issue, see #214.

If I've missed something or should make changes, please let me know. The vignette (and article) files are described by their own issue #218.

**Comment by lwaldron** [comment]
See https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5862039/. @paolinomanghi can you add any relevant text that you have to this issue.
