### ISSUE TITLE
create unit tests

### ISSUE THREAD

**Issue by schifferl** [waldronlab/curatedMetagenomicData#219]
Each file under the R directory should have a matching unit test using the testthat package. What follows is a list of the R files that need unit tests with a person suggested to work on them in parentheses. Please let me know where to switch names around (or remove them), if I've gotten it wrong. Below the list of R files is a description of what the unit test might do, we can check files off the list when they're ready.

- [ ] `R/curatedMetagenomicData.R` (@cmirzayi)
- [ ] `R/mergeData.R` (@sdgamboa, @schifferl)
- [ ] `R/returnSamples.R` (@sdgamboa)

**R/curatedMetagenomicData.R**
The unit test should check that results with `dryrun` both `TRUE` and `FALSE` are correct, it can check both cases of `print` argument and the `counts` arguments too. When checking the `pattern` argument, a golden test is possible with the `inst/extdata/metadata.csv` file and one should be implemented to check that all posibilites are there - these could also be downloaded and their classes could be checked (the matrices inside the objects too), but this might be prohibitive with the Bioconductor Build System. The latter might be implemented as a long test, but I've never done one so I can't say more than that.

**R/mergeData.R**
All data types should be check for correct merging (the two AsnicarF studies are particularly useful for this) and also differing data types should be checked for failed merging.

**Comment by schifferl** [comment]
@sdgamboa, I just wanted to add a note to work on this one last. The package might change just a little more and I don't want us to have to redo the unit test when it happens.

**Comment by lwaldron** [comment]
Should transport as many of the tests from https://github.com/waldronlab/curatedMetagenomicData/tree/legacy/tests/testthat as possible.

**Comment by schifferl** [comment]
Closed by the addition of 41 test in 7a2a2c3.
