### ISSUE TITLE
Installation problems

### ISSUE THREAD

**Issue by snayfach** [waldronlab/curatedMetagenomicData#223]
Running into a few issues on the install I was hoping you could help with.

I successfully installed the R package from the R command line using:
`BiocManager::install("curatedMetagenomicData")`

However I'm not getting the expected output running the example from the R command line:
`library(curatedMetagenomicData)`
`curatedMetagenomicData("AsnicarF_2017")`
> Dry run: see return values for datasets that would be downloaded. Run with `dryrun=FALSE` to actually download these datasets.  
> character(0)

`curatedMetagenomicData("AsnicarF_2017.relative_abundance", dryrun = FALSE)`
> Error in curatedMetagenomicData("AsnicarF_2017.relative_abundance", dryrun = FALSE) :
> requested datasets do not match any available datasets.

Any ideas what could be wrong?

**Comment by lwaldron** [comment]
Hi @snayfach,

dataset names have changed in version 3.0 (which is what's documented on this GitHub repo now, and which names you're using) compared to 1.x (which is what you have installed from Bioconductor). You can either:

1. look at the vignette on bioconductor.org for usage instructions for your current installation. You'll only have access to ~half as many samples and half as many features compared to 3.0, and this will only continue working for the next few weeks unless you install the legacy package from here (we'll provide instructions with the release for installing the legacy package), or
2. install R-devel and bioc-devel (www.bioconductor.org/devel), then install curatedMetagenomicData 2.99 from GitHub (`BiocManager::install("waldronlab/curatedMetagenomicData")`.

In another few weeks when Bioconductor 3.13 is released, everyone will be using curatedMetagenomicData 3.0 by default.

**Comment by snayfach** [comment]
Thanks for the pointers. Unfortunately I couldn't get the development version of R easily installed (currently running 4.0.3) and the latest version of curatedMetagenomicData requires R >= 4.1. I'm thinking it makes the most sense to wait a few weeks until Bioconductor 3.13 and curatedMetagenomicData 3.0 are released.

Is there any way to download the latest sample metadata table in the meantime?

**Comment by lwaldron** [comment]
Yes, the new metadata are in this repo in the file "combined_metadata.rda" under the "data/" directory. Just download that and load it into R with `load("combined_metadata.rda")`.

**Comment by snayfach** [comment]
Thanks!

**Comment by snayfach** [comment]
Right now there are 20,284 samples in that table (awesome!). Are there any plans in the near-term to expand this metadata a lot, or is this about up to date with current metagenome studies?
