### ISSUE TITLE
Fix R-CMD-check-bioc action

### ISSUE THREAD

**Issue by jwokaty** [waldronlab/curatedMetagenomicData#233]
Fix R-CMD-check-bioc action so that it installs 'gt' for pkgdown along with any other issues.

**Comment by schifferl** [comment]
I fixed the `gt` problem [here](https://github.com/waldronlab/curatedMetagenomicData/blob/master/vignettes/articles/available-studies.Rmd) with lines 17-19 (I think).

**Comment by jwokaty** [comment]
@schifferl Ok, if https://github.com/waldronlab/curatedMetagenomicData/runs/2568148926?check_suite_focus=true passes, I'll close the issue; otherwise, I'll try to fix any remaining issues with the action.

**Comment by schifferl** [comment]
Looks like it passes on Ubuntu, but macOS and windows don't want to check 3.13 packages yet. I'm ok with just Ubuntu for now.
