### ISSUE TITLE
Error using curatedMetagenomicData()

### ISSUE THREAD

**Issue by AndreaQ7** [waldronlab/curatedMetagenomicData#237]
Hello everyone, 
I am experiencing an issue using the package when I try to donwload data from a specific study. I get two type of error message, does anyone have the solution for this type of issue?

```
> curatedMetagenomicData("AsnicarF_2017.pathabundance_relab.stool",dryrun=FALSE)
Working on AsnicarF_2017.pathabundance_relab.stool
Error in UseMethod("filter_") : 
  no applicable method for 'filter_' applied to an object of class "c('tbl_SQLiteConnection', 'tbl_dbi', 'tbl_sql', 'tbl_lazy', 'tbl')"
```

or

```
> curatedMetagenomicData("AsnicarF_2017.pathabundance_relab.stool",dryrun=FALSE)
Working on AsnicarF_2017.pathabundance_relab.stool
Error in UseMethod("filter_") : 
  no applicable method for 'filter_' applied to an object of class "c('tbl_SQLiteConnection', 'tbl_dbi', 'tbl_sql', 'tbl_lazy', 'tbl')"
Inoltre: Warning messages:
1: `select_()` was deprecated in dplyr 0.7.0.
Please use `select()` instead.
This warning is displayed once every 8 hours.
Call `lifecycle::last_warnings()` to see where this warning was generated. 
2: `filter_()` was deprecated in dplyr 0.7.0.
Please use `filter()` instead.
See vignette('programming') for more help
This warning is displayed once every 8 hours.
Call `lifecycle::last_warnings()` to see where this warning was generated. 
```

thanks

**Comment by lwaldron** [comment]
Hi @AndreaQ7, would you provide your sessionInfo()? There are big changes happening in R and cMD right now.

**Comment by lwaldron** [comment]
What's happening is that you're using pre-May 2020 versions of R and Bioconductor, but have updated other packages from CRAN like dplyr (possibly using install.packages?), so you have a mixture of package versions that haven't been tested together and won't work. In general with actively developed packages like dplyr and curatedMetagenomicData you'll have to keep up with the R and Bioconductor releases, or use a frozen package library or container image, to use software combinations that are tested and work together. R 4.1 was released yesterday and Bioconductor 3.13 will be released today, so I recommend that tomorrow you install the new R and Bioconductor, then use 
```
install.packages("BiocManager") BiocManager::install("curatedMetagenomicData")
```
to start over with the new release of curatedMetagenomicData 3.0. There are some major changes, most notably the provision of SummarizedExperiment and TreeSummarizedExperiment objects, so it will require some updating of your code, but it will be worth it!

**Comment by AndreaQ7** [comment]
Thanks a lot for your support, tomorrow I will try it

**Comment by schifferl** [comment]
Hi @AndreaQ7, have you been able to try curatedMetagenomicData 3.0.0? Please let us know if we should close the issue.

**Comment by AndreaQ7** [comment]
Yes thank you I have tried it right yestaerday and it works for me

**Comment by schifferl** [comment]
Great! Closing the issue.
