### ISSUE TITLE
no resources available in curatedMetagenomicData

### ISSUE THREAD

**Issue by kevinrue** [waldronlab/curatedMetagenomicData#246]
I picked up a workshop being written for BioC2021, and tried to update it with the template github action workflow for workshops https://github.com/seandavi/BuildABiocWorkshop as an effort to help the author to prepare their workshop for the conference.

I run into the error
```
no resources available in curatedMetagenomicData
```
here in the workflow
https://github.com/kevinrue/EpiForBioWorkshop2021/runs/2847132850?check_suite_focus=true#step:9:18

I'm not a `curatedMetagenomicData` user myself, so I'm not familiar with that error. Does that sound any familiar to you and is there an easy fix?

Thanks!

**Comment by kevinrue** [comment]
OK, so digging a bit more it seems that the workshop queries a resources that's not available (anymore? right now?)

```
> curatedMetagenomicData(pattern = "VogtmannE")
2021-03-31.VogtmannE_2016.gene_families
2021-03-31.VogtmannE_2016.marker_abundance
2021-03-31.VogtmannE_2016.marker_presence
2021-03-31.VogtmannE_2016.pathway_abundance
2021-03-31.VogtmannE_2016.pathway_coverage
2021-03-31.VogtmannE_2016.relative_abundance
```

While the workshop asks for 

```
vogtmann <- curatedMetagenomicData("VogtmannE_2016.metaphlan_bugs_list.stool", dryrun = FALSE)
```

**Comment by schifferl** [comment]
That's old, please read the new documentation and ask your questions on the support site instead.

**Comment by lwaldron** [comment]
Thank you @kevinrue for trying to help fix Chloe's workshop. I've filed an issue under the workshop at https://github.com/cmirzayi/EpiForBioWorkshop2021/issues/2. 

BTW @schifferl, https://waldronlab.io/curatedMetagenomicData/articles/articles/version-three.html doesn't document the changes in naming.
