### ISSUE TITLE
function to add HMP sodiodemographic data

### ISSUE THREAD

**Issue by lwaldron** [waldronlab/curatedMetagenomicData#25]
My thought is a function that takes an HMP ExpressionSet and the local path to the restricted demographic dataset as downloaded from dbGaP, and returns another ExpressionSet with the restricted demographic data added.  

- Function should also be usable for the HMP 16S datasets.
- Function documentation could include instructions on how to obtain and download the dbGaP demographic data.

Lower priority than fixing up the documentation.

**Comment by lwaldron** [comment]
Should be a function(eset, dbgapdir) that returns another ExpressionSet with the dbgap data attached.

**Comment by lwaldron** [comment]
Note to self, make sure to let Curtis Huttenhower, Owen White, and Lauren McIver know when this is ready - they will use it and promote it.

**Comment by schifferl** [comment]
I am going to work on this again – I have the old code that was just never integrated. I will post with progress.

**Comment by schifferl** [comment]
I wonder if we can close this. It is on the roadmap for `HMP16SData` and will be provided there.

**Comment by lwaldron** [comment]
I'd leave it open, since a function should be provided for cMD too and the
form of the datasets is currently different here and would require a
slightly different function. It may also require changes to the template.

On Oct 18, 2017 7:19 AM, "Lucas Schiffer" <notifications@github.com> wrote:

I wonder if we can close this. It is on the roadmap for HMP16SData and will
be provided there.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/waldronlab/curatedMetagenomicData/issues/25#issuecomment-337558405>,
or mute the thread

**Comment by schifferl** [comment]
Ok, leaving open. Thinking we should move towards `SummarizedExperiment` in Bioc 3.7 so that it can potentially be the same function : )

**Comment by lwaldron** [comment]
Yes, I agree with moving to SummarizedExperiment in 3.7!

**Comment by schifferl** [comment]
This issue is very old and more of a feature request (I prefer to keep those on [Trello](https://trello.com/b/FdfktMns)), for that reason I will close it but keep it in mind for something to look into after the 3.13 release.
