### ISSUE TITLE
Add short content with link on README to direct users to CMA

### ISSUE THREAD

**Issue by jwokaty** [waldronlab/curatedMetagenomicData#251]
Add short content with link on README to direct users to curatedMetagenomicAnalyses.

**Comment by schifferl** [comment]
Just a note, this would need to go in the `README.Rmd` file in the `RELEASE_3_13` branch and I will `git cherry-pick` it into the `master` branch. (This is done to make the README package links refer to the release versions of Bioconductor packages, in case you're wondering).
