### ISSUE TITLE
How to compare my own cohort to your database?

### ISSUE THREAD

**Issue by zckoo007** [waldronlab/curatedMetagenomicData#266]
I have a study of metagenome, how can I integrate the analysis with your  database?

I try to run metaphlan3 and huamann3 default parameters，But the result I got is not the same as yours, the relative abundance is too high.

Can you provide the parameters of metaphlan3 and humann3 so that we can compare our own cohorts with your database

Thanks!

**Comment by schifferl** [comment]
Hi @zckoo007, I am sorry it has taken so long to post a response – you can look at the parameters that are used in our Nextflow pipeline [here](https://github.com/seandavi/curatedMetagenomicsNextflow). Hope that helps.
