### ISSUE TITLE
unable to download LeeKa2022 relative abundance

### ISSUE THREAD

**Issue by abhivij** [waldronlab/curatedMetagenomicData#274]
Hi all,
I have installed the latest cMD package from github and it shows LeeKa2022 study metadata. But trying to fetch the relative abundance throws an error

**To Reproduce**

```
sample_metadata_LeeKA2022 <- sampleMetadata %>%
	filter(study_name == "LeeKA_2022")
data <- sample_metadata_LeeKA2022 %>%
	returnSamples("relative_abundance")

```	
snapshotDate(): 2021-05-18
Error: dataType of list elements is different

**Expected behaviour**
relative_abundance data should be available

**Comment by schifferl** [comment]
This is not available yet, please wait for the Bioconductor 3.15 release at the end of the month.
