### ISSUE TITLE
how to access metaphlan_bugs_list.stool data using curatedMetagenomicData 3.6?

### ISSUE THREAD

**Issue by tommyfuu** [waldronlab/curatedMetagenomicData#281]
hi!

I read on the manual [here](https://rdrr.io/github/waldronlab/curatedMetagenomicData/f/NEWS.md) that all the named functions such as `curatedMetagenomicData("AsnicarF_2017.metaphlan_bugs_list.stool")` is now defunct. However, I now became super confused as in how to access the count data/relative abundance data easily with the `curatedMetagenomicData() `function, as it seems that `curatedMetagenomicData("AsnicarF_2017.relative_abundance") `would still work, but it will give me a super long list that I do not understand.

Note that it seems like I am still able to access the metadata just fine using the `returnSamples` function.

**Comment by schifferl** [comment]
Hi @tommyfuu, please read the [curatedMetagenomicData](https://bioconductor.org/packages/release/data/experiment/vignettes/curatedMetagenomicData/inst/doc/curatedMetagenomicData.html) and [TreeSummarizedExperiment](https://bioconductor.org/packages/release/bioc/vignettes/TreeSummarizedExperiment/inst/doc/Introduction_to_treeSummarizedExperiment.html) vignettes.

**Comment by tommyfuu** [comment]
Hi,

Thank you! I actually just figured out after reading [this closed issue](https://github.com/waldronlab/curatedMetagenomicData/issues/277) and realized that I should have tried the 'type conversion' part of the [curatedMetagenomicData](https://bioconductor.org/packages/release/data/experiment/vignettes/curatedMetagenomicData/inst/doc/curatedMetagenomicData.html#mutate-coldata) vignette! Here's my working code in case any future users run into the same question as me:

```
## to access a single study and convert to phyloseq
brooksB2017_metaObj = sampleMetadata |>
    filter(study_name == "BrooksB_2017") |>
    select(where(~ !any(is.na(.x))))  |>
    returnSamples("pathway_abundance", rownames = "short")

brooksB2017_Phyloseq <- brooksB2017_metaObj|> 
  mia::makePhyloseqFromTreeSummarizedExperiment(abund_values="pathway_abundance")
brooksB2017_Phyloseq  <- prune_taxa(taxa_sums(brooksB2017_Phyloseq) >0, brooksB2017_Phyloseq)
```
```
### to access multiple studies and make a phyloseq object
IBD_3sets_metaObj = sampleMetadata |>
    filter(study_name %in% c("HMP_2019_ibdmdb", "IjazUZ_2017", "LiJ_2014")) |>
    select(where(~ !any(is.na(.x))))  |>
    returnSamples("relative_abundance", rownames = "short")

IBD_3sets_Phyloseq <- IBD_3sets_metaObj|> 
  mia::makePhyloseqFromTreeSummarizedExperiment(abund_values="relative_abundance")
IBD_3sets_Phyloseq   <- prune_taxa(taxa_sums(IBD_3sets_Phyloseq ) >0, IBD_3sets_Phyloseq )
```
Hope you have a great day!

**Comment by schifferl** [comment]
Hi @tommyfuu, per the text you deleted to create this issue and the [contributing guidelines](https://github.com/waldronlab/curatedMetagenomicData/blob/master/CONTRIBUTING.md), please post to https://support.bioconductor.org in the future.

> User Support
If something remains unclear after you've thoroughly read all sections of the package website, please don't hesitate to contact us via the Bioconductor support site. Read through the posts at https://support.bioconductor.org/tag/curatedMetagenomicData first; and if there's nothing that helps, ask a question with the `curatedMetagenomicData` tag and we'll respond quickly.

I would have to discourage future users from using your code and would rather suggest the following.

```r
library(curatedMetagenomicData)
library(mia)
library(dplyr)

BrooksB_2017.pathway_abundance <-
    curatedMetagenomicData("BrooksB_2017.pathway_abundance", dryrun = FALSE)[[1L]] |>
    makePhyloseqFromTreeSummarizedExperiment(abund_values = "pathway_abundance")

inflammatoryBowelDisease <-
    filter(sampleMetadata, disease == "IBD") |>
    select(where(~ !all(is.na(.x)))) |>
    returnSamples("relative_abundance") |>
    makePhyloseqFromTreeSummarizedExperiment(abund_values = "relative_abundance")
``` 

If for some reason only the three IBD studies were desired rather than all the IBD samples, I would make the following modification to the code above.

```r
inflammatoryBowelDisease <-
    curatedMetagenomicData("(HMP_2019_ibdmdb|IjazUZ_2017|LiJ_2014).relative_abundance", dryrun = FALSE) |>
    mergeData() |>
    makePhyloseqFromTreeSummarizedExperiment(abund_values = "relative_abundance")
```
