### ISSUE TITLE
Error: failed to load resource (name: EH5651)

### ISSUE THREAD

**Issue by ninglijunXGP** [waldronlab/curatedMetagenomicData#282]
hi! can you help me?

when i was downlaod "2021-03-31.LifeLinesDeep_2016.gene_families", there is an error "reason: error in evaluating the argument 'x' in selecting a method for function 'get': error reading from connection", how to address this issue? thank you.

**Comment by ninglijunXGP** [comment]
my download code:

> curatedMetagenomicData::curatedMetagenomicData("2021-03-31.LifeLinesDeep_2016.gene_families", dryrun = FALSE)

**Comment by schifferl** [comment]
Hi @ninglijunXGP, can you try again? Your code works for me, and the error might have been related to the release of Bioconductor 3.16.
