### ISSUE TITLE
Number of curated studies and potential duplicates?

### ISSUE THREAD

**Issue by lyjspx** [waldronlab/curatedMetagenomicData#291]
Hi,

I am writing to you regarding some ambiguities that I encountered while working with the curated datasets. On the available studies page (https://waldronlab.io/curatedMetagenomicData/articles/available-studies.html), there are 93 listed studies/datasets. However, when I queried in R ('curatedMetagenomicData('.', dryrun = T)'), it returned 690 entries, which contained 115 unique studies, such as 2021-03-31.AsnicarF_2017.

I am seeking your assistance in clarifying whether there are any duplicated studies in R. I noticed that some studies appeared in two entries but with different time stamps, which has caused confusion. If there are duplicates, may I kindly request a unique list of datasets?

Best regards,

Yuan

**Comment by schifferl** [comment]
Hi @lyjspx, as this is a user support issue, please post to the [Bioconductor Support Site](https://support.bioconductor.org/) for assistance. This is also outlined [here](https://waldronlab.io/curatedMetagenomicData/reference/curatedMetagenomicData.html).
