### ISSUE TITLE
github.io website

### ISSUE THREAD

**Issue by lwaldron** [waldronlab/curatedMetagenomicData#48]

**Comment by schifferl** [comment]
https://waldronlab.github.io/curatedMetagenomicData/

**Comment by lwaldron** [comment]
This is great! I like all the links at the top of the page. Would it be hard to add another link to the Issues tracker? Make sure to let everyone know in the meeting notes you send around.

**Comment by schifferl** [comment]
No problem to add an issue tracker link. I am going to switch to another theme though (http://brianmaierjr.com/long-haul/) and build out some of the pages. I will be sure to send out with the meeting notes and close the issue when I'm done.

**Comment by lwaldron** [comment]
No worries, in fact bioconductor.org acts as a public bug reporting site, and it's not even necessary to add that link.

**Comment by schifferl** [comment]
Note to self: add a section about the handoff to R

**Comment by schifferl** [comment]
Not sure if we still need a section about handoff to R, but the site is mostly complete. If there are issues, just make a new issue with more specific tasks. Closing isssue 🥇

**Comment by lwaldron** [comment]
Looks great! A couple quick comments: 1) the things currently under "Tutorials" would belong better in "Installation" (except for "Adding New Data" which belongs more on the Github source page). The Tutorials page could link to the package vignette and extra uncompiled vignettes developed for the manuscript, and redundantly to the tutorials that are already under the publications page. I'll add these under a new issue though.
