### ISSUE TITLE
add TODO datasets to web page

### ISSUE THREAD

**Issue by lwaldron** [waldronlab/curatedMetagenomicData#55]
and invite suggestions for other datasets through this Issues tracker.

**Comment by lwaldron** [comment]
PS the working spreadsheet is [here](https://docs.google.com/spreadsheets/d/1hX9f1j6KkHQ_AdwJf-5eOJfnLemf4LHuGkB-bdOPTeA/edit#gid=0).

**Comment by schifferl** [comment]
closed by 8aeef1f
