### ISSUE TITLE
16sRNA studies

### ISSUE THREAD

**Issue by naarkhoo** [waldronlab/curatedMetagenomicData#56]
This is not an issue. I really like the idea and will definitely looking forward using the package; however, I am curious was the package is not covering 16s studies ?

**Comment by lwaldron** [comment]
We do not at this time have a pipeline set up for 16s processing, we would need additional funding to do that on a large scale! However we are working on an equivalent package for 16s data from the HMP: https://github.com/waldronlab/HMP16SData

**Comment by schifferl** [comment]
If only we had the $$$, I would happily write a package!

**Comment by naarkhoo** [comment]
I am sure you there are undergrad students looking for fame and full of ambition that money is not the first on their priority list. Thanks anyway for your work and your comments :-)

**Comment by schifferl** [comment]
Interesting idea, will keep it in mind for the future. Going to close this issue now and glad you like the package 👍

**Comment by lwaldron** [comment]
And if you know a student who would up to the task, let us know, but it's not easy work!
