### ISSUE TITLE
template.csv improvements

### ISSUE THREAD

**Issue by lwaldron** [waldronlab/curatedMetagenomicData#57]
Affects file [template.csv](https://github.com/waldronlab/curatedMetagenomicData/blob/master/inst/extdata/template.csv)

Changes:

bodysite, disease, country: put actual allowable values
age: numeric
country: put a list of all countries
number_reads, pubmedid: integer

@edoardopasolli what is SNPRNT, that we could use for a more descriptive description? Also, method = ss|mock|sw|qq|cut is unclear, and gad-antibodies. Could you look through this file again and try to make it 1) more specific in the allowable values (not * when there are a finite number of allowable values, even if this might have to be updated as we add more datasets), and 2) make the descriptions as user friendly as possible? We will make this file into a searchable data dictionary that makes it easy for users to find and download the datasets they want.

**Comment by lwaldron** [comment]
Some minor issues with inst/extdata/template.csv:
* What do you want to accomplish with `*|unknown` under allowed value? This is the same as `*`.
* In some places an allowed value is "na", in others it's "unknown" - be clear about what the difference between these is, or record missingness in the same way
* allowedvalues shouldn't start or end with a `|` - e.g. for country, stool_texture

**Comment by edoardopasolli** [comment]
template.csv file completely re-done during the rebuilding of the package. several iterations fixed minor issues.

"na" and "unknown" still coexist. we should discuss more about this.

**Comment by schifferl** [comment]
I recognized this point too and handled it during import, treating "na" and "unknown" as equivalent.

```
format_metadata <- function(dataset_dir) {
    metadata_tsv <- paste0(dataset_dir, "metadata/metadata.tsv")
    metadata_cols(metadata_tsv) %>%
    read_tsv(metadata_tsv, col_types = ., na = c("", "NA", "na", "nA", "Na", "unknown", "none"))
}
```

**Comment by edoardopasolli** [comment]
it is correct to collapse "na" and "unknown" into a single class, but "none" should be kept distinct

**Comment by lwaldron** [comment]
Agreed, keep "none" distinct. As we tighten up template.csv and formalize
its checking through a separate branch (issue #78), all this will be
handled during curation.

**Comment by lwaldron** [comment]
"unknown" is now gone, and upper-case "NA" is the only way to record missing values.  See [template.csv](https://github.com/waldronlab/curatedMetagenomicDataCuration/blob/master/inst/extdata/template.csv) in the curatedMetagenomicDataCuration repo.
