### ISSUE TITLE
uncurated_author_metadata

### ISSUE THREAD

**Issue by lwaldron** [waldronlab/curatedMetagenomicData#58]
It is good to have the original, uncurated metadata on hand, to check for variables that weren't included in the curation, or to check for curation errors. In the past I have put this in a final column "uncurated_author_metadata" with entries the following format, and made a function for splitting this into its own dataframe:

`colname1: value///colname2: value///colname3: value`

This also makes curation more manageable, as you can focus on the more commonly recurring variables, without worrying that you are losing the less common variables. @edoardopasolli and Paolo (don't have your ID yet), would you consider adding this column as the last column of the curated metadata?

**Comment by lwaldron** [comment]
That's the syntax I've used, but looking at it now I think this would be better just _in case_ anyone used a single colon in their column header...

`colname1:::value///colname2:::value///colname3:::value`

**Comment by schifferl** [comment]
This issue was moved to waldronlab/curatedMetagenomicDataCuration#15
