### ISSUE TITLE
Keep all rows of humann2 *genefamilies.tsv

### ISSUE THREAD

**Issue by lwaldron** [waldronlab/curatedMetagenomicData#59]
This would be a good use case for use of `Matrix::sparseMatrix` and/or some remote on-disk representation solution, as there would be several million rows. Curtis convinced me that keeping these full rows is more useful than I realized. Please add any comments on potential solutions for a large, relatively sparse matrix. Also FYI @vjcitn @ttriche @schifferl

**Comment by schifferl** [comment]
My current thoughts are that this could be done as promise, only evaluated once requested or using BigQuery might also work, but that wouldn't exactly be consistent with ExperimentHub... I don't remember the exact size of this object but I can make a large one and we can come up with some solutions

**Comment by lwaldron** [comment]
Excellent. @vobencha I think we should think about how to do this in the ExperimentHub framework, akin to the vcf + tabix approach you can use for 1000 genomes on an Amazon S3 bucket.

**Comment by vobencha** [comment]
Hi @lwaldron 

I'm not sure if you want (i) a delayed back-end implementation for the curatedMetagenomicData ExpressionSet objects or (ii)  the ability to read a subset of the object from the S3 bucket or both.

IIUC, the vcf + tabix approach reads distinct subsets and does not 'keep all rows'. If you are interested in just downloading a subset of data from S3 you could write a method that dispatches on an ExperimentHubMetadata object. The function would use the url location in the ExperimentHub metadata (not currently exposed but could be) to download the subset you want. I can explain further if this is what you want.

If you want a delayed back-end for ExpressionSet objects I'd get @hpages involved as he has been doing extensive work in this area.

I don't know that you'd be saving time by implementing a remote delayed back-end (i.e., retrieves from S3 for each realization). I'd think there would be issues with latency and possible connection loss; my guess it that downloading the file once then using a local on-disk representation would be better. I suppose the size of the file and number of repeated access calls would determine the gain.

Val

**Comment by lwaldron** [comment]
Thanks Val! I'm not tied to keeping the ExpressionSet representation of these. It will help having a demo object to look at and compare options, which I understand now as:
1. the vcf + tabix - like approach, which if I understand you correctly would break up the object and download components of it, saving bandwidth
2. a Matrix::sparseMatrix representation, which would save disk space and memory. May be compatible with 1. Have to see how sparse the matrix really is to see if this is worth it.
3. an HDF5 based approach, e.g. delayedArray
4. nothing special

I think there are < 10M rows, and will grow to >10K samples but in different datasets. The largest dataset could eventually be >1,000 samples, so it seems to me there will start to be storage, memory, and bandwidth issues.

**Comment by vobencha** [comment]
See page 3 of [this Rsamtools vignette](https://www.bioconductor.org/help/course-materials/2010/BioC2010/Exercises-Rsamtools.pdf) for an example of downloading protions of a bam file from a url. You first download the index file which is small, then use a 'param' to specify subsets. 

With AnnotationHub >=2.7.14 you can get the physical location of the file with mcols(hub[1])$rdatapath. (rdatapath is exposed in both ExperimentHub and AnnotationHub.) For example,
```
> hub = AnnotationHub()
snapshotDate(): 2017-02-07
> query(hub, "VCF")
AnnotationHub with 8 records
# snapshotDate(): 2017-02-07 
# $dataprovider: dbSNP
# $species: Homo sapiens
# $rdataclass: VcfFile
# additional mcols(): taxonomyid, genome, description,
#   coordinate_1_based, maintainer, rdatadateadded, preparerclass, tags,
#   rdatapath, sourceurl, sourcetype 
# retrieve records with, e.g., 'object[["AH50420"]]' 

            title                                         
  AH50420 | clinvar_20160203.vcf.gz                       
  AH50421 | clinvar_20160203_papu.vcf.gz                  
  AH50422 | common_and_clinical_20160203.vcf.gz           
  AH50423 | common_no_known_medical_impact_20160203.vcf.gz
  AH50424 | clinvar_20160203.vcf.gz                       
  AH50425 | clinvar_20160203_papu.vcf.gz                  
  AH50426 | common_and_clinical_20160203.vcf.gz           
  AH50427 | common_no_known_medical_impact_20160203.vcf.gz
> mcols(hub["AH50420"])$rdatapath
[1] "pub/clinvar/vcf_GRCh37/archive/2016/clinvar_20160203.vcf.gz, pub/clinvar/vcf_GRCh37/archive/2016/clinvar_20160203.vcf.gz.tbi"
```
You can then download the index, create a 'param' object and download subsets of the data with readVcf() or scanVcf() as shown in the Rsamtools vignette for scanBam(). The function that does this (this being (i) download index, (ii) create param and (iii) call readVcf() with the param) would be in your software package, documented with a man page etc.

You would not be using the ExperimentHub / AnnotationHub interface to download the files, just to get the rdatapath. Downloading files can be done with GET() as in AnnotationHub:::.hub_cache_resource(). You would need to pre-pend "http://s3.amazonaws.com/experimenthub/" to the rdatapath.

Val

**Comment by lwaldron** [comment]
@schifferl : try solutions 2 & 3 above (sparseMatrix and a SummarizedExperiment with remote data store, touch base with Vince on setting up the latter).

**Comment by schifferl** [comment]
This issue was moved to waldronlab/curatedMetagenomicDataPipeline#1
