### ISSUE TITLE
HMP PubMed ID is Incorrect

### ISSUE THREAD

**Issue by schifferl** [waldronlab/curatedMetagenomicData#67]
The curated metadata for the HMP dataset incorrectly credits the study as,

> Department of Psychology, Abdul Haq Campus, Federal Urdu University for Arts, Science and Technology, Karachi, Pakistan. shahiq_psy@yahoo.com

the metadata should be corrected and then the documentation and expression sets can be rerun.

**Comment by edoardopasolli** [comment]
all curated metadata files were corrected. so this and other similar metadata errors were corrected when rebuilding the package
