### ISSUE TITLE
Move phyloseq from Depends to Suggests

### ISSUE THREAD

**Issue by lwaldron** [waldronlab/curatedMetagenomicData#71]
See https://github.com/waldronlab/MultiAssayExperiment/issues/199 for advice on what to do if `ExpressionSet2phyloseq()` is called.

**Comment by lwaldron** [comment]
e.g. use this in the function:
```
if (!requireNamespace("phyloseq")) {
  stop("Please install the UpsetR package to make venn diagrams")
}```

**Comment by schifferl** [comment]
This happened some time ago, closing the issue.
