### ISSUE TITLE
Clean up Suggests?

### ISSUE THREAD

**Issue by lwaldron** [waldronlab/curatedMetagenomicData#72]
Is there an advantage for packages that are used in the pipeline, but not part of the curatedMetagenomicData API, to be in Suggests? These aren't used by the curatedMetagenomic package itself, and could be installed as part of the pipeline, e.g. an `install_needed_packages()` function.

**Comment by schifferl** [comment]
The packages in suggest are there as the development dependencies and it seemed like a logical place for them, at least to me. The ExperimentHub API suggests doing source("./inst/scripts/make-data.R") and having this produce the data of the package. We don't use it to produce data but instead load all the functions and packages that will be necessary in producing data from inputs provided by the user. I could do something like `install_needed_packages` if preferred but that just seems like a further abstraction of the same thing. Let me know your thoughts and I will make the necessary changes.

**Comment by lwaldron** [comment]
This will occur as part of the migration of pipeline functions to a separate repo.

**Comment by schifferl** [comment]
Just as an FYI, I am going to do this in the `development` branch and eventually merge back to `master`

**Comment by lwaldron** [comment]
Should be updated/closed with #165 @schifferl

**Comment by lwaldron** [comment]
closed by 221a889861918ba1ef8154f7e84ac5acc388194c
