### ISSUE TITLE
PaperFigures.Rmd

### ISSUE THREAD

**Issue by edoardopasolli** [waldronlab/curatedMetagenomicData#73]
I was able to generate all the figures in the past. But I am getting a couple of errors when trying to regenerate Supplementary Figure 4 now (all the other figures are fine):

Error: could not find function "curatedMetagenomicData"

Error in strsplit(xnames, split = split, fixed = TRUE) : 
  non-character argument

**Comment by schifferl** [comment]
You may need to update the curatedMetagenomicData package, as that function wasn't included until sometime later

**Comment by edoardopasolli** [comment]
you were right
