### ISSUE TITLE
lighten up package

### ISSUE THREAD

**Issue by lwaldron** [waldronlab/curatedMetagenomicData#76]
The help/ directory in particular seems excessive, if it's going to grow linearly with the number of datasets included. I think we can live with data/combined_metadata.RData, one day this can go into the hub when it gets too big.  These can be long term "wish list" items.

```
* checking installed package size ... NOTE
  installed size is 16.0Mb
  sub-directories of 1Mb or more:
    data   7.5Mb
    help   7.9Mb
```

**Comment by lwaldron** [comment]
Actually, I just realized that most of the space in data/ is from the following undocumented datasets - definitely unnecessary bloat:

```
-rw-r--r-- 1 lwaldron lwaldron 5639558 Sep 21  2016 LomanNJ_2013_Mi.genefamilies_relab.stool.rda
-rw-r--r-- 1 lwaldron lwaldron  887824 Sep 21  2016 LomanNJ_2013_Mi.marker_abundance.stool.rda
-rw-r--r-- 1 lwaldron lwaldron  590372 Sep 21  2016 LomanNJ_2013_Mi.marker_presence.stool.rda
-rw-r--r-- 1 lwaldron lwaldron   17203 Sep 21  2016 LomanNJ_2013_Mi.metaphlan_bugs_list.stool.rda
-rw-r--r-- 1 lwaldron lwaldron  180361 Sep 21  2016 LomanNJ_2013_Mi.pathabundance_relab.stool.rda
-rw-r--r-- 1 lwaldron lwaldron  164483 Sep 21  2016 LomanNJ_2013_Mi.pathcoverage.stool.rda
```

**Comment by schifferl** [comment]
This is related to the images included in the documentation, I could shrink and compress them or remove them altogether. I will try both and see if I can get rid of the note.

**Comment by schifferl** [comment]
I optimized the images and this note is now gone. Closing this issue
