### ISSUE TITLE
Create a new branch for curated metadata

### ISSUE THREAD

**Issue by lwaldron** [waldronlab/curatedMetagenomicData#78]
Give this branch a package structure, so that:
* datasets go in inst/extdata
* it depends on curatedMetagenomicData
* in tests/ it loads each dataset and runs it through checkCuration()
* it tests additional issues, like too many PMIDs and illegal NCBI/SRA IDs
* Continuous Integration lets you know if all datasets passed, and log files show you the curation issues

Finally, update CONTRIBUTING.md to explain how to do this. 

@paolinomanghi this will automate all checking of curated metadata...

**Comment by lwaldron** [comment]
This is now its own repository https://github.com/waldronlab/curatedMetagenomicDataCuration

**Comment by paolinomanghi** [comment]
Ok, Levi, perfect. Thanks, I'm going to upload the table e test the
uploading system.

**Comment by schifferl** [comment]
Should this issue be closed now that the new repository was created?

**Comment by lwaldron** [comment]
Next step is to create a tiny package that tests checkCuration() on any tsv
files in inst/, let's leave this issue open for that task.

**Comment by lwaldron** [comment]
Done, see https://github.com/waldronlab/curatedMetagenomicDataCuration
