### ISSUE TITLE
Strip large binaries from history with BFG

### ISSUE THREAD

**Issue by lwaldron** [waldronlab/curatedMetagenomicData#83]
Because large data files were previously included in the git history cloning this repository takes an inordinate amount of time. See the previous issue from MultiAssayExperiment on how large binary data files can be cleaned from the history:

https://github.com/waldronlab/MultiAssayExperiment/issues/44

Note that any forks will have to do the same or to re-fork before issuing a pull request, or else history will re-appear. Better to do this now than after there are even more forks.

**Comment by schifferl** [comment]
On it!

**Comment by schifferl** [comment]
Completed with e0e7372, but the docs site has a few large images that make the repos a bit much to download. To fix, I could move the site to another repos if that makes sense.
