### ISSUE TITLE
Phyloseq error: duplicate rownames with pathabundance_relab.stool

### ISSUE THREAD

**Issue by wipperman** [waldronlab/curatedMetagenomicData#90]
Hello,

There is an error converting taxa_names() from the ExpressionSet object to a Phyloseq object. Running the following two lines of code yields the following error:

hmpstool.eset <- HMP_2012.pathabundance_relab.stool()
hmpstool.pathabundance.phy <- ExpressionSet2phyloseq(hmpstool.eset)

Error in `taxa_names<-`(`*tmp*`, value = gsub("\"", "", taxa_names(x),  : 
  taxa_names<-: You are attempting to assign duplicated taxa_names

One can see that there are indeed duplicate rownames (i.e., multiple pathways with 0s by running this line: 
exprs( hmpstool.eset )

Are there ways/options to merge all duplicate pathways for a single column (i.e., person) together? 

Thanks! --Matt

**Comment by schifferl** [comment]
I believe the ExpressionSet class requires that rownames be unique. I Will try a few things with the code you've provided above and see if I can achieve the conversion. It may be a problem with ExpressionSet2phyloseq and if so I will fix the error. Thanks for the bug report!

**Comment by schifferl** [comment]
Only the `metaphlan_bugs_list` objects should be converted to `phyloseq` objects. I will add a more informative error to the function.

```r
hmpstool.eset <- HMP_2012.metaphlan_bugs_list.stool()
hmpstool.metaphlan.phy <- ExpressionSet2phyloseq(hmpstool.eset)
```

**Comment by schifferl** [comment]
The rownames are indeed unique:
```r
hmpstool.eset <- HMP_2012.pathabundance_relab.stool()
length(unique(rownames(hmpstool.eset))) == nrow(hmpstool.eset)
```
What analysis are you attempting to do using phyloseq?

**Comment by wipperman** [comment]
Try running this additional line:

hmpstool.eset <- HMP_2012.pathabundance_relab.stool()
length(unique(rownames(hmpstool.eset))) == nrow(hmpstool.eset) #this is TRUE 
pseq <- ExpressionSet2phyloseq(hmpstool.eset) #this gives an error 

I also get that rownames are unique, however ExpressionSet2phyloseq will not convert rownames to "OTU names". I think Phyloseq offers many functionalities that would be useful for plotting--I would do the same sort of analyses with pathway data that one would for the bugs list :)

**Comment by schifferl** [comment]
This should do it:
```r
hmpstool.eset <- HMP_2012.pathabundance_relab.stool()
pseq <- ExpressionSet2phyloseq(hmpstool.eset, simplify = FALSE)
```

**Comment by wipperman** [comment]
Great--that does the trick. Thanks so much for the help!

**Comment by schifferl** [comment]
Glad to help!

**Comment by lwaldron** [comment]
Indeed, the default "simplify=TRUE" argument to  `ExpressionSet2phyloseq()` is specific to the MetaPhlAn2 bugs list. @wipperman we didn't expect anyone to want to convert pathway abundances to `phyloseq` objects - what advantage does `phyloseq` offer for these datasets?

**Comment by lwaldron** [comment]
@schifferl rather than return an error if the rownames don't look like metaphlan bugs, perhaps just throw a warning and continue with `simplify=FALSE`?

**Comment by wipperman** [comment]
@lwaldron @schifferl Thanks for all of the feedback! I think there are several great reasons to encourage the use of Phyloseq. I have found it to be a helpful package and means to store large amounts of data. My current code effectively turns dataframes (bugs, RNAseq data, Uniref pathways, etc) into Phyloseq objects, which I can then manipulate using common code. The powerful set of analytical tools once in Phyloseq format (graphics, integration with Vegan, running correlations, etc) I just find comfortable. I suppose it isn't totally necessary, but for 'first pass' analysis, it is helpful to put data + metadata of this type into a phyloseq object, "look" at it, then decide where to go from there. Does that make sense?

**Comment by wipperman** [comment]
@lwaldron @schifferl So I've managed to merge all of the experimental pathway data, however, when I run a PCA analysis on the HUMANN2 data comparing 9 ExperimentHub datasets with my own dataset, there was a clear separation between the two. I think I am running "default" Humann2 parameters, but I don't know how to confirm this. Do you have a detailed example of what the exact Humann2 parameters are for the overall analysis? I should note that the separation that I get on a PCA plot is perfect when I compare the Metaphlan2 data (i.e., there is a biologically-sensible pattern), so it must be something with the parameters to convert Uniref gene data to pathway abundance. Thanks so much for the help!

**Comment by schifferl** [comment]
@wipperman please see the files [here](https://github.com/waldronlab/curatedMetagenomicData/tree/master/inst/pipeline)

**Comment by edoardopasolli** [comment]
@wipperman give a look in particular at the file curatedMetagenomicData_pipeline.sh (lines 43-45) to see how you can normalize the different data products
