### ISSUE TITLE
participant metadata files now end in _metadata.tsv

### ISSUE THREAD

**Issue by lwaldron** [waldronlab/curatedMetagenomicData#91]
I changed per-participant metadata files from `_metadata.txt` to `_metadata.tsv` at https://github.com/waldronlab/curatedMetagenomicDataCuration, to take advantage of [GitHub's automatic rendering of tsv files](https://help.github.com/articles/rendering-csv-and-tsv-data/). Make any changes necessary in the script and R pipelines. @edoardopasolli @paolinomanghi @schifferl .

**Comment by paolinomanghi** [comment]
Ok

**Comment by schifferl** [comment]
Thanks for the heads up 👍

**Comment by schifferl** [comment]
No known issues related to the change – closing this issue
