### ISSUE TITLE
Accessing VincentC_2016

### ISSUE THREAD

**Issue by matthpich** [waldronlab/curatedMetagenomicData#94]
Hi,
Thanks for the great program
From this page https://waldronlab.github.io/curatedMetagenomicData/datasets-included/, VincentC_2016 dataset is now supposedly available.
I cannot access this dataset, while I can access datasets from the initial program release.
Is it expected?
Best,
M

**Comment by schifferl** [comment]
Hello,
This is the expected behavior. The VincentC_2016 dataset is indeed available but you will need to use Bioc-Devel. Are you familar with the procedure of how to switch between the release and devel software?
Thanks,
Lucas

**Comment by matthpich** [comment]
Nope.
I will have a look.
Thanks for your quick answer.
Best wishes,
M

2017-08-07 18:39 GMT-04:00 Lucas Schiffer <notifications@github.com>:

**Comment by schifferl** [comment]
The long answer is here (https://bioconductor.org/developers/how-to/useDevel/) but the essence of the instructions are a few R commands, as follows.
```
library(BiocInstaller)
useDevel()
biocLite()
```
This will switch you over to the devel software and `VincentC_2016` will be available.

I will see that the documentation is updated to reflect that devel must be used.

Thanks for using the package!

**Comment by lwaldron** [comment]
@matthpich we will make this more clear on the github.io website and the README.md - thank you for bringing it to our attention.

**Comment by matthpich** [comment]
Sounds great.
Thanks again for your very thorough answer and the great package.
