### ISSUE TITLE
Question: what was the scope of the Uniref database used for curatedMetagenomicData?

### ISSUE THREAD

**Issue by seandavi** [waldronlab/curatedMetagenomicData#98]
Noting that there are several flavors of Uniref available via humann2 download, which version is used for curatedMetagenomicData?

https://bitbucket.org/biobakery/humann2/wiki/Home#markdown-header-5-download-the-databases

**Comment by edoardopasolli** [comment]
We use the "full UniRef90 database (11.0GB, recommended)" that can be downloaded via humann2 download

**Comment by seandavi** [comment]
Thanks for confirming, @edoardopasolli.
